In [ ]:
import requests
import json
import pandas as pd

In [ ]:
url = "https://data.sec.gov/api/xbrl/companyfacts/CIK0000789019.json"
response = requests.get(url)

In [ ]:
response.status_code

403

In [ ]:
headers = {
    "User-Agent": "YourName your@email.com"
}

response = requests.get(url, headers=headers)

In [ ]:
response.status_code

200

In [ ]:
data = response.json()

In [ ]:
type(data)

dict

In [ ]:
data.keys()

dict_keys(['cik', 'entityName', 'facts'])

In [ ]:
data["cik"]

789019

In [ ]:
data["entityName"]

'MICROSOFT CORPORATION'

In [ ]:
data["facts"].keys()

dict_keys(['dei', 'us-gaap'])

In [ ]:
data["facts"]["us-gaap"].keys()

dict_keys(['AccountsPayableCurrent', 'AccountsReceivableNet', 'AccountsReceivableNetCurrent', 'AccountsReceivableNetNoncurrent', 'AccruedIncomeTaxesCurrent', 'AccruedIncomeTaxesNoncurrent', 'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', 'AccumulatedOtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossCumulativeChangesInNetGainLossFromCashFlowHedgesEffectNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'AcquiredFiniteLivedIntangibleAssetAmount', 'AcquiredFiniteLivedIntangibleAssetWeightedAverageUsefulLife', 'AdvertisingExpense', 'AllocatedShareBasedCompensationExpense', 'AllowanceForDoubtfulAccountsReceivableCurrent', 'AmortizationOfIntangibleAssets', 'AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount', 'AssetImpairmentCharges', 'Assets', 'AssetsCurrent', 'AssetsFairValueDisclosureRecurring', 'AvailableForSaleDebtSecuritiesAmortizedCostBasis', 'AvailableForSaleSecurities', 'AvailableForSaleSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', 'AvailableForSaleSecuritiesAccumulatedGrossUnrealizedLossBeforeTax', 'AvailableForSaleSecuritiesAmortizedCost', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionFairValue', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThanTwelveMonthsFairValue', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionTwelveMonthsOrLongerFairValue', 'AvailableForSaleSecuritiesCurrent', 'AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearFairValue', 'AvailableForSaleSecuritiesDebtSecurities', 'AvailableForSaleSecuritiesGrossRealizedGains', 'AvailableForSaleSecuritiesGrossRealizedLosses', 'AvailableForSaleSecuritiesGrossUnrealizedLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAggregateLosses2', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionAggregateLosses2', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAggregateLosses2', 'AvailableforsaleSecuritiesGrossUnrealizedGain', 'BuildingsAndImprovementsGross', 'BusinessAcquisitionCostOfAcquiredEntityCashPaid', 'BusinessAcquisitionProFormaEarningsPerShareDiluted', 'BusinessAcquisitionsProFormaNetIncomeLoss', 'BusinessAcquisitionsProFormaRevenue', 'BusinessCombinationIntegrationRelatedCosts', 'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedIntangibles', 'CapitalizedComputerSoftwareAmortization', 'CapitalizedComputerSoftwareAmortization1', 'CapitalLeasedAssetsGross', 'CapitalLeaseObligationsIncurred', 'CapitalLeasesFutureMinimumPaymentsDue', 'CapitalLeasesFutureMinimumPaymentsDueCurrent', 'CapitalLeasesFutureMinimumPaymentsDueInFiveYears', 'CapitalLeasesFutureMinimumPaymentsDueInFourYears', 'CapitalLeasesFutureMinimumPaymentsDueInThreeYears', 'CapitalLeasesFutureMinimumPaymentsDueInTwoYears', 'CapitalLeasesFutureMinimumPaymentsDueThereafter', 'CapitalLeasesFutureMinimumPaymentsInterestIncludedInPayments', 'CapitalLeasesFutureMinimumPaymentsRemainderOfFiscalYear', 'CapitalLeasesLesseeBalanceSheetAssetsByMajorClassAccumulatedDeprecation', 'CashAndCashEquivalentsAtCarryingValue', 'CashAndCashEquivalentsPeriodIncreaseDecrease', 'CashCashEquivalentsAndShortTermInvestments', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect', 'CommercialPaper', 'CommonStockDividendsPerShareDeclared', 'CommonStockIncludingAdditionalPaidInCapital', 'CommonStockSharesAuthorized', 'CommonStockSharesOutstanding', 'CommonStocksIncludingAdditionalPaidInCapital', 'ComprehensiveIncomeNetOfTax', 'ContractWithCustomerLiability', 'ContractWithCustomerLiabilityCurrent', 'ContractWithCustomerLiabilityNoncurrent', 'ContractWithCustomerLiabilityRevenueRecognized', 'ConvertibleDebtCurrent', 'CostMethodInvestments', 'CostOfGoodsAndServicesSold', 'CostOfGoodsSold', 'CostOfRevenue', 'CostsAndExpenses', 'CumulativeEffectOfInitialAdoptionOfFIN48', 'CumulativeEffectOfInitialAdoptionOfNewAccountingPrinciple', 'CurrentFederalTaxExpenseBenefit', 'CurrentForeignTaxExpenseBenefit', 'CurrentIncomeTaxExpenseBenefit', 'CurrentStateAndLocalTaxExpenseBenefit', 'DebtInstrumentCarryingAmount', 'DebtInstrumentFaceAmount', 'DebtInstrumentPrincipalOutstanding', 'DebtInstrumentUnamortizedDiscount', 'DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet', 'DebtLongtermAndShorttermCombinedAmount', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLonger', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12Months', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'DebtSecuritiesAvailableForSaleRealizedGain', 'DebtSecuritiesAvailableForSaleRealizedLoss', 'DebtSecuritiesAvailableForSaleUnrealizedLossPosition', 'DebtSecuritiesAvailableForSaleUnrealizedLossPositionAccumulatedLoss', 'DeferredFederalIncomeTaxExpenseBenefit', 'DeferredFederalStateAndLocalTaxExpenseBenefit', 'DeferredForeignIncomeTaxExpenseBenefit', 'DeferredIncomeTaxExpenseBenefit', 'DeferredIncomeTaxesAndTaxCredits', 'DeferredIncomeTaxLiabilities', 'DeferredIncomeTaxLiabilitiesNet', 'DeferredRevenue', 'DeferredRevenueAdditions', 'DeferredRevenueCurrent', 'DeferredRevenueNoncurrent', 'DeferredRevenueRevenueRecognized', 'DeferredRevenueRevenueRecognized1', 'DeferredStateAndLocalIncomeTaxExpenseBenefit', 'DeferredTaxAssetsCapitalLossCarryforwards', 'DeferredTaxAssetsDeferredIncome', 'DeferredTaxAssetsGross', 'DeferredTaxAssetsLiabilitiesNet', 'DeferredTaxAssetsLiabilitiesNetCurrent', 'DeferredTaxAssetsLiabilitiesNetNoncurrent', 'DeferredTaxAssetsNet', 'DeferredTaxAssetsNetCurrent', 'DeferredTaxAssetsNetNoncurrent', 'DeferredTaxAssetsOperatingLossCarryforwards', 'DeferredTaxAssetsOther', 'DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost', 'DeferredTaxAssetsTaxDeferredExpenseOther', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsImpairmentLosses', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsOther', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsRestructuringCharges', 'DeferredTaxAssetsValuationAllowance', 'DeferredTaxLiabilities', 'DeferredTaxLiabilitiesLeasingArrangements', 'DeferredTaxLiabilitiesNoncurrent', 'DeferredTaxLiabilitiesOther', 'DeferredTaxLiabilitiesOtherComprehensiveIncome', 'DeferredTaxLiabilitiesTaxDeferredIncome', 'DeferredTaxLiabilitiesUndistributedForeignEarnings', 'DeferredTaxLiabilityNotRecognizedAmountOfUnrecognizedDeferredTaxLiability', 'DeferredTaxLiabilityNotRecognizedAmountOfUnrecognizedDeferredTaxLiabilityUndistributedEarningsOfForeignSubsidiaries', 'DeferredTaxLiabilityNotRecognizedCumulativeAmountOfTemporaryDifference', 'DefinedContributionPlanCostRecognized', 'DefinedContributionPlanEmployerMatchingContributionPercentOfMatch', 'DefinedContributionPlanMaximumAnnualContributionPerEmployeePercent', 'DefinedContributionPlanMaximumAnnualContributionsPerEmployeePercent', 'DepositsReceivedForSecuritiesLoanedAtCarryingValue', 'Depreciation', 'DerivativeAssetDesignatedAsHedgingInstrumentFairValue', 'DerivativeAssetFairValueGrossAssetIncludingNotSubjectToMasterNettingArrangement', 'DerivativeAssetFairValueGrossLiability', 'DerivativeAssetNotDesignatedAsHedgingInstrumentFairValue', 'DerivativeAssets', 'DerivativeCollateralObligationToReturnCash', 'DerivativeCollateralRightToReclaimCash', 'DerivativeFairValueOfDerivativeAsset', 'DerivativeFairValueOfDerivativeLiability', 'DerivativeInstrumentsNotDesignatedAsHedgingInstrumentsGainLossNet', 'DerivativeLiabilities', 'DerivativeLiabilityFairValueGrossAsset', 'DerivativeLiabilityFairValueGrossLiabilityIncludingNotSubjectToMasterNettingArrangement', 'DerivativePriceRiskOptionStrikePrice', 'DividendsCommonStockCash', 'DividendsStock', 'EarningsPerShareBasic', 'EarningsPerShareDiluted', 'EffectiveIncomeTaxRateContinuingOperations', 'EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate', 'EffectiveIncomeTaxRateReconciliationDeductionsQualifiedProductionActivities', 'EffectiveIncomeTaxRateReconciliationForeignIncomeTaxRateDifferential', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpense', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost', 'EffectiveIncomeTaxRateReconciliationOtherAdjustments', 'EffectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes', 'EffectiveIncomeTaxRateReconciliationTaxCreditsResearch', 'EffectiveIncomeTaxRateReconciliationTaxSettlementsDomestic', 'EffectOfExchangeRateOnCashAndCashEquivalents', 'EmployeeRelatedLiabilitiesCurrent', 'EmployeeServiceShareBasedCompensationCashReceivedFromExerciseOfStockOptions', 'EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense', 'EmployeeServiceShareBasedCompensationTaxBenefitRealizedFromExerciseOfStockOptions', 'EntityWideDisclosureOnGeographicAreasLongLivedAssetsInEntitysCountryOfDomicile', 'EntityWideDisclosureOnGeographicAreasLongLivedAssetsInForeignCountries', 'EntityWideDisclosureOnGeographicAreasRevenueFromExternalCustomersAttributedToEntitysCountryOfDomicile', 'EntityWideDisclosureOnGeographicAreasRevenueFromExternalCustomersAttributedToForeignCountries', 'EquitySecuritiesFvNiRealizedGainLoss', 'EquitySecuritiesFvNiUnrealizedGainLoss', 'EquitySecuritiesWithoutReadilyDeterminableFairValueAmount', 'ExcessTaxBenefitFromShareBasedCompensationFinancingActivities', 'ExcessTaxBenefitFromShareBasedCompensationOperatingActivities', 'FairValueAssetsMeasuredOnRecurringBasisCashAndCashEquivalents', 'FairValueAssetsMeasuredOnRecurringBasisChangeInUnrealizedGainLossIncludedInOtherIncome', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInEarnings', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInEarnings1', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInOtherComprehensiveIncome', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInOtherComprehensiveIncomeLoss', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetPurchases', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetPurchasesSalesIssuancesSettlements', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetTransfersNet', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetTransfersOutOfLevel3', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', 'FinanceLeaseInterestExpense', 'FinanceLeaseInterestPaymentOnLiability', 'FinanceLeaseLiability', 'FinanceLeaseLiabilityPaymentsDue', 'FinanceLeaseLiabilityPaymentsDueAfterYearFive', 'FinanceLeaseLiabilityPaymentsDueNextTwelveMonths', 'FinanceLeaseLiabilityPaymentsDueYearFive', 'FinanceLeaseLiabilityPaymentsDueYearFour', 'FinanceLeaseLiabilityPaymentsDueYearThree', 'FinanceLeaseLiabilityPaymentsDueYearTwo', 'FinanceLeaseLiabilityPaymentsRemainderOfFiscalYear', 'FinanceLeaseLiabilityUndiscountedExcessAmount', 'FinanceLeasePrincipalPayments', 'FinanceLeaseRightOfUseAsset', 'FinanceLeaseRightOfUseAssetAmortization', 'FinanceLeaseWeightedAverageDiscountRatePercent', 'FiniteLivedIntangibleAssetsAccumulatedAmortization', 'FiniteLivedIntangibleAssetsAmortizationExpense', 'FiniteLivedIntangibleAssetsAmortizationExpenseAfterYearFive', 'FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths', 'FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFive', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFour', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearThree', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo', 'FiniteLivedIntangibleAssetsGross', 'FiniteLivedIntangibleAssetsNet', 'FiniteLivedIntangibleAssetsUsefulLifeMaximum', 'FiniteLivedIntangibleAssetsUsefulLifeMinimum', 'FinitelivedIntangibleAssetsAcquired1', 'ForeignCurrencyCashFlowHedgeGainLossReclassifiedToEarningsNet', 'ForeignCurrencyCashFlowHedgeGainLossToBeReclassifiedDuringNext12Months', 'ForeignCurrencyTransactionGainLossBeforeTax', 'FurnitureAndFixturesGross', 'FutureAmortizationExpenseAfterYearFive', 'FutureAmortizationExpenseYearFive', 'FutureAmortizationExpenseYearFour', 'FutureAmortizationExpenseYearOne', 'FutureAmortizationExpenseYearThree', 'FutureAmortizationExpenseYearTwo', 'GainLossOnComponentsExcludedFromAssessmentOfForeignCurrencyCashFlowHedgeEffectiveness', 'GainLossOnDerivativeInstrumentsNetPretax', 'GainLossOnInvestments', 'GeneralAndAdministrativeExpense', 'Goodwill', 'GoodwillAcquiredDuringPeriod', 'GoodwillImpairedAccumulatedImpairmentLoss', 'GoodwillImpairmentLoss', 'GoodwillOtherChanges', 'GoodwillOtherIncreaseDecrease', 'GoodwillWrittenOffRelatedToSaleOfBusinessUnit', 'GrossProfit', 'HeldToMaturitySecurities', 'HeldToMaturitySecuritiesAccumulatedUnrecognizedHoldingGain', 'HeldToMaturitySecuritiesAccumulatedUnrecognizedHoldingLoss', 'HeldToMaturitySecuritiesAmortizedCostBeforeOtherThanTemporaryImpairment', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionLessThanTwelveMonthsFairValue', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionTwelveMonthsOrLongerFairValue', 'HeldToMaturitySecuritiesFairValue', 'ImpairmentEffectOnEarningsPerShareAfterTax', 'ImpairmentOfInvestments', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesDomestic', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments', 'IncomeTaxExpenseBenefit', 'IncomeTaxesPaidNet', 'IncreaseDecreaseInAccountsPayable', 'IncreaseDecreaseInAccountsReceivable', 'IncreaseDecreaseInAccruedIncomeTaxesPayable', 'IncreaseDecreaseInCashCollateralForLoanedSecurities', 'IncreaseDecreaseInCollateralHeldUnderSecuritiesLending', 'IncreaseDecreaseInContractWithCustomerLiability', 'IncreaseDecreaseInDeferredRevenue', 'IncreaseDecreaseInInventories', 'IncreaseDecreaseInOtherCurrentAssets', 'IncreaseDecreaseInOtherCurrentLiabilities', 'IncreaseDecreaseInOtherNoncurrentAssets', 'IncreaseDecreaseInOtherNoncurrentLiabilities', 'IncrementalCommonSharesAttributableToShareBasedPaymentArrangements', 'IntangibleAssetsNetExcludingGoodwill', 'InterestExpense', 'InterestPaid', 'InventoryAdjustments', 'InventoryFinishedGoods', 'InventoryFinishedGoodsNetOfReserves', 'InventoryNet', 'InventoryRawMaterials', 'InventoryRawMaterialsNetOfReserves', 'InventoryWorkInProcess', 'InventoryWorkInProcessNetOfReserves', 'InvestmentIncomeInterestAndDividend', 'InvestmentIncomeNet', 'Land', 'LeaseAndRentalExpense', 'LeaseholdImprovementsGross', 'LesseeOperatingLeaseLiabilityPaymentsDue', 'LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFour', 'LesseeOperatingLeaseLiabilityPaymentsDueYearThree', 'LesseeOperatingLeaseLiabilityPaymentsDueYearTwo', 'LesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear', 'LesseeOperatingLeaseLiabilityUndiscountedExcessAmount', 'Liabilities', 'LiabilitiesAndStockholdersEquity', 'LiabilitiesCurrent', 'LineOfCreditFacilityCurrentBorrowingCapacity', 'LineOfCreditFacilityMaximumBorrowingCapacity', 'LitigationReserveNoncurrent', 'LongTermDebt', 'LongTermDebtCurrent', 'LongTermDebtFairValue', 'LongTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo', 'LongTermDebtMaturitiesRepaymentsOfPrincipalRemainderOfFiscalYear', 'LongTermDebtNoncurrent', 'LongTermInvestments', 'LongTermNotesPayable', 'LossContingencyAccrualCarryingValueCurrent', 'LossContingencyRangeOfPossibleLossPortionNotAccrued', 'MarketableSecuritiesRealizedGainLossOtherThanTemporaryImpairmentsAmount', 'MinorityInterestOwnershipPercentageByParent', 'NetCashProvidedByUsedInFinancingActivities', 'NetCashProvidedByUsedInFinancingActivitiesContinuingOperations', 'NetCashProvidedByUsedInInvestingActivities', 'NetCashProvidedByUsedInInvestingActivitiesContinuingOperations', 'NetCashProvidedByUsedInOperatingActivities', 'NetCashProvidedByUsedInOperatingActivitiesContinuingOperations', 'NetIncomeLoss', 'NoncashOrPartNoncashAcquisitionFixedAssetsAcquired1', 'NoncurrentAssets', 'NonoperatingIncomeExpense', 'NumberOfBusinessesAcquired', 'NumberOfReportableSegments', 'OperatingExpenses', 'OperatingIncomeLoss', 'OperatingLeaseCost', 'OperatingLeaseImpairmentLoss', 'OperatingLeaseLiability', 'OperatingLeaseLiabilityNoncurrent', 'OperatingLeasePayments', 'OperatingLeaseRightOfUseAsset', 'OperatingLeaseWeightedAverageDiscountRatePercent', 'OperatingLossCarryforwards', 'OptionIndexedToIssuersEquityStrikePrice', 'OtherAccruedLiabilitiesNoncurrent', 'OtherAssets', 'OtherAssetsCurrent', 'OtherAssetsFairValueDisclosure', 'OtherAssetsNoncurrent', 'OtherComprehensiveIncomeAvailableForSaleSecuritiesAdjustmentNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationAdjustmentNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeForeignCurrencyTranslationAdjustmentTax', 'OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'OtherComprehensiveIncomeLossAvailableForSaleSecuritiesTax', 'OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTax', 'OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesNetOfTax', 'OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesTax', 'OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax', 'OtherComprehensiveIncomeLossForeignCurrency

In [ ]:
data["facts"]["us-gaap"]["Revenues"]

{'label': 'Revenues',
 'description': 'Amount of revenue recognized from goods sold, services rendered, insurance premiums, or other activities that constitute an earning process. Includes, but is not limited to, investment and interest income before deduction of interest expense when recognized as a component of revenue, and sales and trading gain (loss).',
 'units': {'USD': [{'start': '2007-07-01',
    'end': '2007-09-30',
    'val': 13762000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2007Q3'},
   {'start': '2007-10-01',
    'end': '2007-12-31',
    'val': 16367000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2007Q4'},
   {'start': '2008-01-01',
    'end': '2008-03-31',
    'val': 14454000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008Q1'},
   {'start': '2007-07-01',
    'end': '2008-06-30',
    'val': 60420000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008'},
   {'start': '2008-04-01',
    'end': '2008-06-30',
    'val': 15837000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008Q2'},
   {'start': '2008-07-01',
    'end': '2008-09-30',
    'val': 15061000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008Q3'},
   {'start': '2008-07-01',
    'end': '2008-09-30',
    'val': 15061000000,
    'accn': '0001193125-09-212454',
    'fy': 2010,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2009-10-23'},
   {'start': '2008-07-01',
    'end': '2008-12-31',
    'val': 31690000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2008-10-01',
    'end': '2008-12-31',
    'val': 16629000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008Q4'},
   {'start': '2008-10-01',
    'end': '2008-12-31',
    'val': 16629000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2008-07-01',
    'end': '2009-03-31',
    'val': 45338000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2009-01-01',
    'end': '2009-03-31',
    'val': 13648000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2009Q1'},
   {'start': '2009-01-01',
    'end': '2009-03-31',
    'val': 13648000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2008-07-01',
    'end': '2009-06-30',
    'val': 58437000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2009'},
   {'start': '2009-04-01',
    'end': '2009-06-30',
    'val': 13099000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2009Q2'},
   {'start': '2009-07-01',
    'end': '2009-09-30',
    'val': 12920000000,
    'accn': '0001193125-10-239825',
    'fy': 2011,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2010-10-28',
    'frame': 'CY2009Q3'},
   {'start': '2009-07-01',
    'end': '2009-09-30',
    'val': 12920000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30'},
   {'start': '2009-07-01',
    'end': '2009-09-30',
    'val': 12920000000,
    'accn': '0001193125-09-212454',
    'fy': 2010,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2009-10-23'},
   {'start': '2009-07-01',
    'end': '2009-12-31',
    'val': 31942000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27'},
   {'start': '2009-07-01',
    'end': '2009-12-31',
    'val': 31942000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2009-10-01',
    'end': '2009-12-31',
    'val': 19022000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27',
    'frame': 'CY2009Q4'},
   {'start': '2009-10-01',
    'end': '2009-12-31',
    'val': 19022000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30'},
   {'start': '2009-10-01',
    'end': '2009-12-31',
    'val': 19022000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2009-07-01',
    'end': '2010-03-31',
    'val': 46445000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2010-01-01',
    'end': '2010-03-31',
    'val': 14503000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2010Q1'},
   {'start': '2010-01-01',
    'end': '2010-03-31',
    'val': 14503000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2009-07-01',
    'end': '2010-06-30',
    'val': 62484000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2010'},
   {'start': '2010-04-01',
    'end': '2010-06-30',
    'val': 16039000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2010Q2'},
   {'start': '2010-07-01',
    'end': '2010-09-30',
    'val': 16195000000,
    'accn': '0001193125-10-239825',
    'fy': 2011,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2010-10-28',
    'frame': 'CY2010Q3'},
   {'start': '2010-07-01',
    'end': '2010-12-31',
    'val': 36148000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27'},
   {'start': '2010-10-01',
    'end': '2010-12-31',
    'val': 19953000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27',
    'frame': 'CY2010Q4'}]}}

In [ ]:
len(data["facts"]["us-gaap"]["Revenues"]["units"]["USD"])

31

In [ ]:
revenue = data["facts"]["us-gaap"]["Revenues"]["units"]["USD"]

annual_revenue = [item for item in revenue if item["fp"] == "FY"]

len(annual_revenue)

15

In [ ]:
annual_revenue

[{'start': '2007-07-01',
  'end': '2007-09-30',
  'val': 13762000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2007Q3'},
 {'start': '2007-10-01',
  'end': '2007-12-31',
  'val': 16367000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2007Q4'},
 {'start': '2008-01-01',
  'end': '2008-03-31',
  'val': 14454000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008Q1'},
 {'start': '2007-07-01',
  'end': '2008-06-30',
  'val': 60420000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008'},
 {'start': '2008-04-01',
  'end': '2008-06-30',
  'val': 15837000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008Q2'},
 {'start': '2008-07-01',
  'end': '2008-09-30',
  'val': 15061000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008Q3'},
 {'start': '2008-10-01',
  'end': '2008-12-31',
  'val': 16629000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008Q4'},
 {'start': '2009-01-01',
  'end': '2009-03-31',
  'val': 13648000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2009Q1'},
 {'start': '2008-07-01',
  'end': '2009-06-30',
  'val': 58437000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2009'},
 {'start': '2009-04-01',
  'end': '2009-06-30',
  'val': 13099000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2009Q2'},
 {'start': '2009-07-01',
  'end': '2009-09-30',
  'val': 12920000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30'},
 {'start': '2009-10-01',
  'end': '2009-12-31',
  'val': 19022000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30'},
 {'start': '2010-01-01',
  'end': '2010-03-31',
  'val': 14503000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2010Q1'},
 {'start': '2009-07-01',
  'end': '2010-06-30',
  'val': 62484000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2010'},
 {'start': '2010-04-01',
  'end': '2010-06-30',
  'val': 16039000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2010Q2'}]

In [ ]:
annual_revenue = [
    item for item in revenue
    if item["fp"] == "FY"
    and item["form"] == "10-K"
    and item["end"].endswith("-06-30")
]

In [ ]:
len(annual_revenue)

6

In [ ]:
annual_revenue

[{'start': '2007-07-01',
  'end': '2008-06-30',
  'val': 60420000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008'},
 {'start': '2008-04-01',
  'end': '2008-06-30',
  'val': 15837000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2008Q2'},
 {'start': '2008-07-01',
  'end': '2009-06-30',
  'val': 58437000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2009'},
 {'start': '2009-04-01',
  'end': '2009-06-30',
  'val': 13099000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2009Q2'},
 {'start': '2009-07-01',
  'end': '2010-06-30',
  'val': 62484000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2010'},
 {'start': '2010-04-01',
  'end': '2010-06-30',
  'val': 16039000000,
  'accn': '0001193125-10-171791',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-07-30',
  'frame': 'CY2010Q2'}]

In [ ]:
start = pd.to_datetime("2009-07-01")
end = pd.to_datetime("2010-06-30")

end - start

Timedelta('364 days 00:00:00')

In [ ]:
revenue_df = pd.DataFrame(revenue)

In [ ]:
revenue_df.head()

,start,end,val,accn,fy,fp,form,filed,frame
0,2007-07-01,2007-09-30,13762000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2007Q3
1,2007-10-01,2007-12-31,16367000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2007Q4
2,2008-01-01,2008-03-31,14454000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2008Q1
3,2007-07-01,2008-06-30,60420000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2008
4,2008-04-01,2008-06-30,15837000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2008Q2

In [ ]:
revenue_df["start"] = pd.to_datetime(revenue_df["start"])
revenue_df["end"] = pd.to_datetime(revenue_df["end"])

In [ ]:
revenue_df["duration"] = revenue_df["end"] - revenue_df["start"]

In [ ]:
revenue_df[["start", "end", "duration"]].head(10)

       start        end duration
0 2007-07-01 2007-09-30  91 days
1 2007-10-01 2007-12-31  91 days
2 2008-01-01 2008-03-31  90 days
3 2007-07-01 2008-06-30 365 days
4 2008-04-01 2008-06-30  90 days
5 2008-07-01 2008-09-30  91 days
6 2008-07-01 2008-09-30  91 days
7 2008-07-01 2008-12-31 183 days
8 2008-10-01 2008-12-31  91 days
9 2008-10-01 2008-12-31  91 days

In [ ]:
annual_revenue = revenue_df[
    revenue_df["duration"] == pd.Timedelta(days=365)
]

In [ ]:
annual_revenue

,start,end,val,accn,fy,fp,form,filed,frame,duration
3,2007-07-01,2008-06-30,60420000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2008,365 days

In [ ]:
annual_revenue = revenue_df[
    (revenue_df["duration"] >= pd.Timedelta(days=350))
    &
    (revenue_df["duration"] <= pd.Timedelta(days=380))
]

In [ ]:
len(annual_revenue)

3

In [ ]:
revenue_df["duration"].value_counts().sort_index()

duration
89 days      4
90 days      4
91 days     14
183 days     4
273 days     2
364 days     2
365 days     1
Name: count, dtype: int64

In [ ]:
annual_revenue[["start", "end", "val", "fy", "form", "filed", "frame"]]

        start        end          val    fy  form       filed   frame
3  2007-07-01 2008-06-30  60420000000  2010  10-K  2010-07-30  CY2008
13 2008-07-01 2009-06-30  58437000000  2010  10-K  2010-07-30  CY2009
26 2009-07-01 2010-06-30  62484000000  2010  10-K  2010-07-30  CY2010

In [ ]:
revenue_df.tail(10)

,start,end,val,accn,fy,fp,form,filed,frame,duration
21,2009-10-01,2009-12-31,19022000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,NaN,91 days
22,2009-10-01,2009-12-31,19022000000,0001193125-10-015598,2010,Q2,10-Q,2010-01-28,NaN,91 days
23,2009-07-01,2010-03-31,46445000000,0001193125-10-090116,2010,Q3,10-Q,2010-04-22,NaN,273 days
24,2010-01-01,2010-03-31,14503000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2010Q1,89 days
25,2010-01-01,2010-03-31,14503000000,0001193125-10-090116,2010,Q3,10-Q,2010-04-22,NaN,89 days
26,2009-07-01,2010-06-30,62484000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2010,364 days
27,2010-04-01,2010-06-30,16039000000,0001193125-10-171791,2010,FY,10-K,2010-07-30,CY2010Q2,90 days
28,2010-07-01,2010-09-30,16195000000,0001193125-10-239825,2011,Q1,10-Q,2010-10-28,CY2010Q3,91 days
29,2010-07-01,2010-12-31,36148000000,0001193125-11-015947,2011,Q2,10-Q,2011-01-27,NaN,183 days
30,2010-10-01,2010-12-31,19953000000,0001193125-11-015947,2011,Q2,10-Q,2011-01-27,CY2010Q4,91 days

In [ ]:
revenue_new = data["facts"]["us-gaap"]["RevenueFromContractWithCustomerExcludingAssessedTax"]["units"]["USD"]

len(revenue_new)

134

In [ ]:
revenue_new[-5:]

[{'start': '2025-07-01',
  'end': '2025-12-31',
  'val': 158946000000,
  'accn': '0001193125-26-027207',
  'fy': 2026,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2026-01-28'},
 {'start': '2025-10-01',
  'end': '2025-12-31',
  'val': 81273000000,
  'accn': '0001193125-26-027207',
  'fy': 2026,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2026-01-28',
  'frame': 'CY2025Q4'},
 {'start': '2025-07-01',
  'end': '2026-03-31',
  'val': 241832000000,
  'accn': '0001193125-26-191507',
  'fy': 2026,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2026-04-29'},
 {'start': '2026-01-01',
  'end': '2026-03-31',
  'val': 82886000000,
  'accn': '0001193125-26-191507',
  'fy': 2026,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2026-04-29',
  'frame': 'CY2026Q1'},
 {'start': '2025-07-01',
  'end': '2026-06-30',
  'val': 331839000000,
  'accn': '0001193125-26-323660',
  'fy': 2026,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2026-07-29',
  'frame': 'CY2026'}]

In [ ]:
revenue_new_df = pd.DataFrame(revenue_new)

In [ ]:
revenue_new_df.head()

,start,end,val,accn,fy,fp,form,filed,frame
0,2015-07-01,2016-06-30,91154000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016
1,2016-07-02,2016-09-30,21928000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016Q3
2,2016-10-01,2016-12-31,25826000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016Q4
3,2017-01-01,2017-03-31,23212000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2017Q1
4,2016-07-01,2017-06-30,96571000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,NaN

In [ ]:
revenue_new_df[["start", "end", "val", "fy", "fp", "form", "filed"]].tail(10)

          start         end           val      fy  fp  form       filed
124  2025-01-01  2025-03-31   70066000000  2025.0  Q3  10-Q  2025-04-30
125  2025-01-01  2025-03-31   70066000000  2026.0  Q3  10-Q  2026-04-29
126  2024-07-01  2025-06-30  281724000000  2025.0  FY  10-K  2025-07-30
127  2024-07-01  2025-06-30  281724000000  2026.0  FY  10-K  2026-07-29
128  2025-07-01  2025-09-30   77673000000  2026.0  Q1  10-Q  2025-10-29
129  2025-07-01  2025-12-31  158946000000  2026.0  Q2  10-Q  2026-01-28
130  2025-10-01  2025-12-31   81273000000  2026.0  Q2  10-Q  2026-01-28
131  2025-07-01  2026-03-31  241832000000  2026.0  Q3  10-Q  2026-04-29
132  2026-01-01  2026-03-31   82886000000  2026.0  Q3  10-Q  2026-04-29
133  2025-07-01  2026-06-30  331839000000  2026.0  FY  10-K  2026-07-29

In [ ]:
revenue_new_df["start"] = pd.to_datetime(revenue_new_df["start"])
revenue_new_df["end"] = pd.to_datetime(revenue_new_df["end"])

In [ ]:
revenue_new_df["duration"] = revenue_new_df["end"] - revenue_new_df["start"]

In [ ]:
revenue_new_df[["start", "end", "duration"]].tail(10)

         start        end duration
124 2025-01-01 2025-03-31  89 days
125 2025-01-01 2025-03-31  89 days
126 2024-07-01 2025-06-30 364 days
127 2024-07-01 2025-06-30 364 days
128 2025-07-01 2025-09-30  91 days
129 2025-07-01 2025-12-31 183 days
130 2025-10-01 2025-12-31  91 days
131 2025-07-01 2026-03-31 273 days
132 2026-01-01 2026-03-31  89 days
133 2025-07-01 2026-06-30 364 days

In [ ]:
annual_revenue = revenue_new_df[
    (revenue_new_df["duration"] >= pd.Timedelta(days=350)) &
    (revenue_new_df["duration"] <= pd.Timedelta(days=380))
]

In [ ]:
annual_revenue[["start", "end", "val", "fy", "fp", "form", "filed"]]

         start        end           val      fy    fp  form       filed
0   2015-07-01 2016-06-30   91154000000  2018.0    FY  10-K  2018-08-03
4   2016-07-01 2017-06-30   96571000000  2018.0    FY  10-K  2018-08-03
5   2016-07-01 2017-06-30   96571000000  2019.0    FY  10-K  2019-08-01
18  2017-07-01 2018-06-30  110360000000  2018.0    FY  10-K  2018-08-03
19  2017-07-01 2018-06-30  110360000000  2019.0    FY  10-K  2019-08-01
20  2017-07-01 2018-06-30  110360000000  2020.0    FY  10-K  2020-07-30
39  2018-07-01 2019-06-30  125843000000  2019.0    FY  10-K  2019-08-01
40  2018-07-01 2019-06-30  125843000000  2020.0    FY  10-K  2020-07-30
41  2018-07-01 2019-06-30  125843000000  2021.0    FY  10-K  2021-07-29
57  2019-07-01 2020-06-30  143015000000  2020.0    FY  10-K  2020-07-30
58  2019-07-01 2020-06-30  143015000000  2021.0    FY  10-K  2021-07-29
59  2019-07-01 2020-06-30  143015000000  2022.0    FY  10-K  2022-07-28
71  2020-07-01 2021-06-30  168088000000  2021.0    FY  10-K  2021-07-29
72  2020-07-01 2021-06-30  168088000000  2022.0    FY  10-K  2022-07-28
73  2020-07-01 2021-06-30  168088000000  2023.0    FY  10-K  2023-07-27
84  2021-07-01 2022-06-30  198270000000  2022.0    FY  10-K  2022-07-28
85  2021-07-01 2022-06-30  198270000000  2023.0    FY  10-K  2023-07-27
86  2021-07-01 2022-06-30  198270000000  2024.0    FY  10-K  2024-07-30
87  2021-07-01 2022-06-30  198270000000     NaN  None   8-K  2024-12-03
98  2022-07-01 2023-06-30  211915000000  2023.0    FY  10-K  2023-07-27
99  2022-07-01 2023-06-30  211915000000  2024.0    FY  10-K  2024-07-30
100 2022-07-01 2023-06-30  211915000000     NaN  None   8-K  2024-12-03
101 2022-07-01 2023-06-30  211915000000  2025.0    FY  10-K  2025-07-30
112 2023-07-01 2024-06-30  245122000000  2024.0    FY  10-K  2024-07-30
113 2023-07-01 2024-06-30  245122000000     NaN  None   8-K  2024-12-03
114 2023-07-01 2024-06-30  245122000000  2025.0    FY  10-K  2025-07-30
115 2023-07-01 2024-06-30  245122000000  2026.0    FY  10-K  2026-07-29
126 2024-07-01 2025-06-30  281724000000  2025.0    FY  10-K  2025-07-30
127 2024-07-01 2025-06-30  281724000000  2026.0    FY  10-K  2026-07-29
133 2025-07-01 2026-06-30  331839000000  2026.0    FY  10-K  2026-07-29

In [ ]:
annual_revenue["form"].value_counts()

form
10-K    27
8-K      3
Name: count, dtype: int64

In [ ]:
annual_revenue[annual_revenue["form"] == "10-K"][["start", "end", "val", "fy", "form", "filed"]]

         start        end           val      fy  form       filed
0   2015-07-01 2016-06-30   91154000000  2018.0  10-K  2018-08-03
4   2016-07-01 2017-06-30   96571000000  2018.0  10-K  2018-08-03
5   2016-07-01 2017-06-30   96571000000  2019.0  10-K  2019-08-01
18  2017-07-01 2018-06-30  110360000000  2018.0  10-K  2018-08-03
19  2017-07-01 2018-06-30  110360000000  2019.0  10-K  2019-08-01
20  2017-07-01 2018-06-30  110360000000  2020.0  10-K  2020-07-30
39  2018-07-01 2019-06-30  125843000000  2019.0  10-K  2019-08-01
40  2018-07-01 2019-06-30  125843000000  2020.0  10-K  2020-07-30
41  2018-07-01 2019-06-30  125843000000  2021.0  10-K  2021-07-29
57  2019-07-01 2020-06-30  143015000000  2020.0  10-K  2020-07-30
58  2019-07-01 2020-06-30  143015000000  2021.0  10-K  2021-07-29
59  2019-07-01 2020-06-30  143015000000  2022.0  10-K  2022-07-28
71  2020-07-01 2021-06-30  168088000000  2021.0  10-K  2021-07-29
72  2020-07-01 2021-06-30  168088000000  2022.0  10-K  2022-07-28
73  2020-07-01 2021-06-30  168088000000  2023.0  10-K  2023-07-27
84  2021-07-01 2022-06-30  198270000000  2022.0  10-K  2022-07-28
85  2021-07-01 2022-06-30  198270000000  2023.0  10-K  2023-07-27
86  2021-07-01 2022-06-30  198270000000  2024.0  10-K  2024-07-30
98  2022-07-01 2023-06-30  211915000000  2023.0  10-K  2023-07-27
99  2022-07-01 2023-06-30  211915000000  2024.0  10-K  2024-07-30
101 2022-07-01 2023-06-30  211915000000  2025.0  10-K  2025-07-30
112 2023-07-01 2024-06-30  245122000000  2024.0  10-K  2024-07-30
114 2023-07-01 2024-06-30  245122000000  2025.0  10-K  2025-07-30
115 2023-07-01 2024-06-30  245122000000  2026.0  10-K  2026-07-29
126 2024-07-01 2025-06-30  281724000000  2025.0  10-K  2025-07-30
127 2024-07-01 2025-06-30  281724000000  2026.0  10-K  2026-07-29
133 2025-07-01 2026-06-30  331839000000  2026.0  10-K  2026-07-29

In [ ]:
annual_10k = annual_revenue[annual_revenue["form"] == "10-K"].copy()

annual_10k = annual_10k.sort_values("filed")

In [ ]:
annual_10k = annual_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_10k[["start", "end", "val", "fy", "form", "filed"]]

         start        end           val      fy  form       filed
0   2015-07-01 2016-06-30   91154000000  2018.0  10-K  2018-08-03
5   2016-07-01 2017-06-30   96571000000  2019.0  10-K  2019-08-01
20  2017-07-01 2018-06-30  110360000000  2020.0  10-K  2020-07-30
41  2018-07-01 2019-06-30  125843000000  2021.0  10-K  2021-07-29
59  2019-07-01 2020-06-30  143015000000  2022.0  10-K  2022-07-28
73  2020-07-01 2021-06-30  168088000000  2023.0  10-K  2023-07-27
86  2021-07-01 2022-06-30  198270000000  2024.0  10-K  2024-07-30
101 2022-07-01 2023-06-30  211915000000  2025.0  10-K  2025-07-30
115 2023-07-01 2024-06-30  245122000000  2026.0  10-K  2026-07-29
127 2024-07-01 2025-06-30  281724000000  2026.0  10-K  2026-07-29
133 2025-07-01 2026-06-30  331839000000  2026.0  10-K  2026-07-29

In [ ]:
annual_10k["fiscal_year"] = annual_10k["end"].dt.year

In [ ]:
revenue_final = annual_10k[["fiscal_year", "val"]].copy()

In [ ]:
revenue_final = revenue_final.rename(columns={"val": "revenue"})

In [ ]:
revenue_final

     fiscal_year       revenue
0           2016   91154000000
5           2017   96571000000
20          2018  110360000000
41          2019  125843000000
59          2020  143015000000
73          2021  168088000000
86          2022  198270000000
101         2023  211915000000
115         2024  245122000000
127         2025  281724000000
133         2026  331839000000

In [ ]:
revenue_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 133
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   fiscal_year  11 non-null     int32
 1   revenue      11 non-null     int64
dtypes: int32(1), int64(1)
memory usage: 520.0 bytes

In [ ]:
revenue_final.isna().sum()

fiscal_year    0
revenue        0
dtype: int64

In [ ]:
revenue_final.sort_values("fiscal_year")

     fiscal_year       revenue
0           2016   91154000000
5           2017   96571000000
20          2018  110360000000
41          2019  125843000000
59          2020  143015000000
73          2021  168088000000
86          2022  198270000000
101         2023  211915000000
115         2024  245122000000
127         2025  281724000000
133         2026  331839000000

In [ ]:
revenue_final["revenue_growth"] = revenue_final["revenue"].pct_change() * 100

In [ ]:
revenue_final

     fiscal_year       revenue  revenue_growth
0           2016   91154000000             NaN
5           2017   96571000000        5.942690
20          2018  110360000000       14.278614
41          2019  125843000000       14.029540
59          2020  143015000000       13.645574
73          2021  168088000000       17.531727
86          2022  198270000000       17.956071
101         2023  211915000000        6.882030
115         2024  245122000000       15.669962
127         2025  281724000000       14.932156
133         2026  331839000000       17.788687

In [ ]:
revenue_final = revenue_final.sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
revenue_final

    fiscal_year       revenue  revenue_growth
0          2016   91154000000             NaN
1          2017   96571000000        5.942690
2          2018  110360000000       14.278614
3          2019  125843000000       14.029540
4          2020  143015000000       13.645574
5          2021  168088000000       17.531727
6          2022  198270000000       17.956071
7          2023  211915000000        6.882030
8          2024  245122000000       15.669962
9          2025  281724000000       14.932156
10         2026  331839000000       17.788687

In [ ]:
cost = data["facts"]["us-gaap"]["CostOfRevenue"]

In [ ]:
cost.keys()

dict_keys(['label', 'description', 'units'])

In [ ]:
cost["units"].keys()

dict_keys(['USD'])

In [ ]:
cost_revenue = cost["units"]["USD"]

In [ ]:
cost_revenue_df = pd.DataFrame(cost_revenue)

In [ ]:
cost_revenue_df.tail(10)

,start,end,val,accn,fy,fp,form,filed,frame
110,2016-07-01,2017-03-31,25805000000,0001564590-17-007547,2017.0,Q3,10-Q,2017-04-27,NaN
111,2016-07-01,2017-03-31,25805000000,0001564590-18-009307,2018.0,Q3,10-Q,2018-04-26,NaN
112,2017-01-01,2017-03-31,8060000000,0001564590-17-007547,2017.0,Q3,10-Q,2017-04-27,NaN
113,2017-01-01,2017-03-31,8060000000,0001564590-18-009307,2018.0,Q3,10-Q,2018-04-26,CY2017Q1
114,2016-07-01,2017-06-30,34261000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2017
115,2017-07-01,2017-09-30,8278000000,0001564590-17-020171,2018.0,Q1,10-Q,2017-10-26,CY2017Q3
116,2017-07-01,2017-12-31,19342000000,0001564590-18-001129,2018.0,Q2,10-Q,2018-01-31,NaN
117,2017-10-01,2017-12-31,11064000000,0001564590-18-001129,2018.0,Q2,10-Q,2018-01-31,CY2017Q4
118,2017-07-01,2018-03-31,28611000000,0001564590-18-009307,2018.0,Q3,10-Q,2018-04-26,NaN
119,2018-01-01,2018-03-31,9269000000,0001564590-18-009307,2018.0,Q3,10-Q,2018-04-26,CY2018Q1

In [ ]:
cost_revenue_df["start"] = pd.to_datetime(cost_revenue_df["start"])
cost_revenue_df["end"] = pd.to_datetime(cost_revenue_df["end"])

In [ ]:
cost_revenue_df["duration"] = cost_revenue_df["end"] - cost_revenue_df["start"]

In [ ]:
cost_revenue_df["duration"].value_counts().sort_index()

duration
89 days     14
90 days      4
91 days     36
183 days    18
273 days    14
274 days     4
364 days    23
365 days     7
Name: count, dtype: int64

In [ ]:
annual_cost = cost_revenue_df[
    (cost_revenue_df["duration"] >= pd.Timedelta(days=350)) &
    (cost_revenue_df["duration"] <= pd.Timedelta(days=380))
]

In [ ]:
annual_cost_10k = annual_cost[annual_cost["form"] == "10-K"].copy()

In [ ]:
annual_cost_10k[["start", "end", "val", "fy", "form", "filed"]]

         start        end          val      fy  form       filed
0   2007-07-01 2008-06-30  11598000000  2010.0  10-K  2010-07-30
6   2008-07-01 2009-06-30  12155000000  2010.0  10-K  2010-07-30
7   2008-07-01 2009-06-30  12155000000  2011.0  10-K  2011-07-28
18  2009-07-01 2010-06-30  12395000000  2010.0  10-K  2010-07-30
19  2009-07-01 2010-06-30  12395000000  2011.0  10-K  2011-07-28
20  2009-07-01 2010-06-30  12395000000  2012.0  10-K  2012-07-26
31  2010-07-01 2011-06-30  15577000000  2011.0  10-K  2011-07-28
32  2010-07-01 2011-06-30  15577000000  2012.0  10-K  2012-07-26
33  2010-07-01 2011-06-30  15577000000  2013.0  10-K  2013-07-30
45  2011-07-01 2012-06-30  17530000000  2012.0  10-K  2012-07-26
46  2011-07-01 2012-06-30  17530000000  2013.0  10-K  2013-07-30
48  2011-07-01 2012-06-30  17530000000  2014.0  10-K  2014-07-31
59  2012-07-01 2013-06-30  20249000000  2013.0  10-K  2013-07-30
61  2012-07-01 2013-06-30  20249000000  2014.0  10-K  2014-07-31
62  2012-07-01 2013-06-30  20385000000  2015.0  10-K  2015-07-31
74  2013-07-01 2014-06-30  26934000000  2014.0  10-K  2014-07-31
75  2013-07-01 2014-06-30  27078000000  2015.0  10-K  2015-07-31
77  2013-07-01 2014-06-30  27078000000  2016.0  10-K  2016-07-28
88  2014-07-01 2015-06-30  33038000000  2015.0  10-K  2015-07-31
90  2014-07-01 2015-06-30  33038000000  2016.0  10-K  2016-07-28
91  2014-07-01 2015-06-30  33038000000  2017.0  10-K  2017-08-02
102 2015-07-01 2016-06-30  32780000000  2016.0  10-K  2016-07-28
103 2015-07-01 2016-06-30  32780000000  2017.0  10-K  2017-08-02
114 2016-07-01 2017-06-30  34261000000  2017.0  10-K  2017-08-02

In [ ]:
annual_cost_10k = annual_cost_10k.sort_values("filed")

annual_cost_10k = annual_cost_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_cost_10k[["start", "end", "val", "filed"]]

         start        end          val       filed
0   2007-07-01 2008-06-30  11598000000  2010-07-30
7   2008-07-01 2009-06-30  12155000000  2011-07-28
20  2009-07-01 2010-06-30  12395000000  2012-07-26
33  2010-07-01 2011-06-30  15577000000  2013-07-30
48  2011-07-01 2012-06-30  17530000000  2014-07-31
62  2012-07-01 2013-06-30  20385000000  2015-07-31
77  2013-07-01 2014-06-30  27078000000  2016-07-28
103 2015-07-01 2016-06-30  32780000000  2017-08-02
91  2014-07-01 2015-06-30  33038000000  2017-08-02
114 2016-07-01 2017-06-30  34261000000  2017-08-02

In [ ]:
annual_cost_10k["fiscal_year"] = annual_cost_10k["end"].dt.year

In [ ]:
cost_final = annual_cost_10k[["fiscal_year", "val"]].copy()

cost_final = cost_final.rename(
    columns={"val": "cost_of_revenue"}
)

cost_final = cost_final.sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
cost_final

   fiscal_year  cost_of_revenue
0         2008      11598000000
1         2009      12155000000
2         2010      12395000000
3         2011      15577000000
4         2012      17530000000
5         2013      20385000000
6         2014      27078000000
7         2015      33038000000
8         2016      32780000000
9         2017      34261000000

In [ ]:
financials = revenue_final.merge(
    cost_final,
    on="fiscal_year",
    how="inner"
)

In [ ]:
financials

   fiscal_year      revenue  revenue_growth  cost_of_revenue
0         2016  91154000000             NaN      32780000000
1         2017  96571000000         5.94269      34261000000

In [ ]:
cost_concepts = [
    key for key in data["facts"]["us-gaap"].keys()
    if "Cost" in key
]

cost_concepts

['AvailableForSaleDebtSecuritiesAmortizedCostBasis',
 'AvailableForSaleSecuritiesAmortizedCost',
 'AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsAmortizedCost',
 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsAmortizedCost',
 'AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsAmortizedCost',
 'AvailableForSaleSecuritiesDebtMaturitiesAmortizedCost',
 'AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsAmortizedCostBasis',
 'AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenAmortizedCostBasis',
 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenAmortizedCostBasis',
 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveAmortizedCostBasis',
 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearAmortizedCost',
 'BusinessAcquisitionCostOfAcquiredEntityCashPaid',
 'BusinessCombinationIntegrationRelatedCosts',
 'CostMethodInvestments',
 'CostOfGoodsAndServicesSold',
 'CostOfGoodsSold',
 'CostOfRevenue',
 'CostsAndExpenses',
 'DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet',
 'DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost',
 'DefinedContributionPlanCostRecognized',
 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost',
 'HeldToMaturitySecuritiesAmortizedCostBeforeOtherThanTemporaryImpairment',
 'OperatingLeaseCost',
 'PaymentsOfDebtExtinguishmentCosts',
 'PaymentsOfDebtRestructuringCosts',
 'RestructuringAndRelatedCostExpectedCostRemaining1',
 'RestructuringAndRelatedCostNumberOfPositionsEliminatedInceptionToDate',
 'SeveranceCosts',
 'SeveranceCosts1',
 'RestructuringAndRelatedCostExpectedNumberOfPositionsEliminated']

In [ ]:
for concept in ["CostOfGoodsSold", "CostOfGoodsAndServicesSold"]:
    print(concept)
    print(data["facts"]["us-gaap"][concept]["units"].keys())

CostOfGoodsSold
dict_keys(['USD'])
CostOfGoodsAndServicesSold
dict_keys(['USD'])

In [ ]:
for concept in ["CostOfGoodsSold", "CostOfGoodsAndServicesSold"]:
    df = pd.DataFrame(
        data["facts"]["us-gaap"][concept]["units"]["USD"]
    )

    df["end"] = pd.to_datetime(df["end"])

    print("\n", concept)
    print(df["end"].max())

 CostOfGoodsSold
2018-03-31 00:00:00

 CostOfGoodsAndServicesSold
2026-06-30 00:00:00

In [ ]:
cost_new = data["facts"]["us-gaap"]["CostOfGoodsAndServicesSold"]["units"]["USD"]

cost_new_df = pd.DataFrame(cost_new)

cost_new_df.tail(10)

,start,end,val,accn,fy,fp,form,filed,frame
100,2025-01-01,2025-03-31,21919000000,0000950170-25-061046,2025.0,Q3,10-Q,2025-04-30,NaN
101,2025-01-01,2025-03-31,21919000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,CY2025Q1
102,2024-07-01,2025-06-30,87831000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,NaN
103,2024-07-01,2025-06-30,87831000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025
104,2025-07-01,2025-09-30,24043000000,0001193125-25-256321,2026.0,Q1,10-Q,2025-10-29,CY2025Q3
105,2025-07-01,2025-12-31,50021000000,0001193125-26-027207,2026.0,Q2,10-Q,2026-01-28,NaN
106,2025-10-01,2025-12-31,25978000000,0001193125-26-027207,2026.0,Q2,10-Q,2026-01-28,CY2025Q4
107,2025-07-01,2026-03-31,76849000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,NaN
108,2026-01-01,2026-03-31,26828000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,CY2026Q1
109,2025-07-01,2026-06-30,106374000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026

In [ ]:
cost_new_df["start"] = pd.to_datetime(cost_new_df["start"])
cost_new_df["end"] = pd.to_datetime(cost_new_df["end"])

In [ ]:
cost_new_df["duration"] = cost_new_df["end"] - cost_new_df["start"]

In [ ]:
annual_cost_new = cost_new_df[
    (cost_new_df["duration"] >= pd.Timedelta(days=350)) &
    (cost_new_df["duration"] <= pd.Timedelta(days=380))
]

In [ ]:
annual_cost_new_10k = annual_cost_new[
    annual_cost_new["form"] == "10-K"
]

In [ ]:
annual_cost_new_10k[["start", "end", "val", "fy", "form", "filed"]]

         start        end           val      fy  form       filed
0   2015-07-01 2016-06-30   32780000000  2018.0  10-K  2018-08-03
1   2016-07-01 2017-06-30   34261000000  2018.0  10-K  2018-08-03
2   2016-07-01 2017-06-30   34261000000  2019.0  10-K  2019-08-01
8   2017-07-01 2018-06-30   38353000000  2018.0  10-K  2018-08-03
9   2017-07-01 2018-06-30   38353000000  2019.0  10-K  2019-08-01
10  2017-07-01 2018-06-30   38353000000  2020.0  10-K  2020-07-30
21  2018-07-01 2019-06-30   42910000000  2019.0  10-K  2019-08-01
22  2018-07-01 2019-06-30   42910000000  2020.0  10-K  2020-07-30
23  2018-07-01 2019-06-30   42910000000  2021.0  10-K  2021-07-29
34  2019-07-01 2020-06-30   46078000000  2020.0  10-K  2020-07-30
35  2019-07-01 2020-06-30   46078000000  2021.0  10-K  2021-07-29
36  2019-07-01 2020-06-30   46078000000  2022.0  10-K  2022-07-28
47  2020-07-01 2021-06-30   52232000000  2021.0  10-K  2021-07-29
48  2020-07-01 2021-06-30   52232000000  2022.0  10-K  2022-07-28
49  2020-07-01 2021-06-30   52232000000  2023.0  10-K  2023-07-27
60  2021-07-01 2022-06-30   62650000000  2022.0  10-K  2022-07-28
61  2021-07-01 2022-06-30   62650000000  2023.0  10-K  2023-07-27
62  2021-07-01 2022-06-30   62650000000  2024.0  10-K  2024-07-30
74  2022-07-01 2023-06-30   65863000000  2023.0  10-K  2023-07-27
75  2022-07-01 2023-06-30   65863000000  2024.0  10-K  2024-07-30
77  2022-07-01 2023-06-30   65863000000  2025.0  10-K  2025-07-30
88  2023-07-01 2024-06-30   74114000000  2024.0  10-K  2024-07-30
90  2023-07-01 2024-06-30   74114000000  2025.0  10-K  2025-07-30
91  2023-07-01 2024-06-30   74114000000  2026.0  10-K  2026-07-29
102 2024-07-01 2025-06-30   87831000000  2025.0  10-K  2025-07-30
103 2024-07-01 2025-06-30   87831000000  2026.0  10-K  2026-07-29
109 2025-07-01 2026-06-30  106374000000  2026.0  10-K  2026-07-29

In [ ]:
annual_cost_new_10k = annual_cost_new_10k.sort_values("filed")

annual_cost_new_10k = annual_cost_new_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_cost_new_10k[["start", "end", "val", "filed"]]

         start        end           val       filed
0   2015-07-01 2016-06-30   32780000000  2018-08-03
2   2016-07-01 2017-06-30   34261000000  2019-08-01
10  2017-07-01 2018-06-30   38353000000  2020-07-30
23  2018-07-01 2019-06-30   42910000000  2021-07-29
36  2019-07-01 2020-06-30   46078000000  2022-07-28
49  2020-07-01 2021-06-30   52232000000  2023-07-27
62  2021-07-01 2022-06-30   62650000000  2024-07-30
77  2022-07-01 2023-06-30   65863000000  2025-07-30
91  2023-07-01 2024-06-30   74114000000  2026-07-29
103 2024-07-01 2025-06-30   87831000000  2026-07-29
109 2025-07-01 2026-06-30  106374000000  2026-07-29

In [ ]:
annual_cost_new_10k["fiscal_year"] = annual_cost_new_10k["end"].dt.year

In [ ]:
cost_final = annual_cost_new_10k[
    ["fiscal_year", "val"]
].copy()

cost_final = cost_final.rename(
    columns={"val": "cost_of_revenue"}
)

cost_final = cost_final.sort_values(
    "fiscal_year"
).reset_index(drop=True)

In [ ]:
cost_final

    fiscal_year  cost_of_revenue
0          2016      32780000000
1          2017      34261000000
2          2018      38353000000
3          2019      42910000000
4          2020      46078000000
5          2021      52232000000
6          2022      62650000000
7          2023      65863000000
8          2024      74114000000
9          2025      87831000000
10         2026     106374000000

In [ ]:
financials = revenue_final.merge(
    cost_final,
    on="fiscal_year",
    how="inner"
)

In [ ]:
financials

    fiscal_year       revenue  revenue_growth  cost_of_revenue
0          2016   91154000000             NaN      32780000000
1          2017   96571000000        5.942690      34261000000
2          2018  110360000000       14.278614      38353000000
3          2019  125843000000       14.029540      42910000000
4          2020  143015000000       13.645574      46078000000
5          2021  168088000000       17.531727      52232000000
6          2022  198270000000       17.956071      62650000000
7          2023  211915000000        6.882030      65863000000
8          2024  245122000000       15.669962      74114000000
9          2025  281724000000       14.932156      87831000000
10         2026  331839000000       17.788687     106374000000

In [ ]:
financials["gross_profit"] = financials["revenue"] - financials["cost_of_revenue"]

In [ ]:
financials

    fiscal_year       revenue  revenue_growth  cost_of_revenue  gross_profit
0          2016   91154000000             NaN      32780000000   58374000000
1          2017   96571000000        5.942690      34261000000   62310000000
2          2018  110360000000       14.278614      38353000000   72007000000
3          2019  125843000000       14.029540      42910000000   82933000000
4          2020  143015000000       13.645574      46078000000   96937000000
5          2021  168088000000       17.531727      52232000000  115856000000
6          2022  198270000000       17.956071      62650000000  135620000000
7          2023  211915000000        6.882030      65863000000  146052000000
8          2024  245122000000       15.669962      74114000000  171008000000
9          2025  281724000000       14.932156      87831000000  193893000000
10         2026  331839000000       17.788687     106374000000  225465000000

In [ ]:
financials["gross_margin"] = financials["gross_profit"] / financials["revenue"] * 100

In [ ]:
financials

,fiscal_year,revenue,revenue_growth,cost_of_revenue,gross_profit,gross_margin
0,2016,91154000000,NaN,32780000000,58374000000,64.038879
1,2017,96571000000,5.942690,34261000000,62310000000,64.522476
2,2018,110360000000,14.278614,38353000000,72007000000,65.247372
3,2019,125843000000,14.029540,42910000000,82933000000,65.901957
4,2020,143015000000,13.645574,46078000000,96937000000,67.781002
5,2021,168088000000,17.531727,52232000000,115856000000,68.925801
6,2022,198270000000,17.956071,62650000000,135620000000,68.401674
7,2023,211915000000,6.882030,65863000000,146052000000,68.920086
8,2024,245122000000,15.669962,74114000000,171008000000,69.764444
9,2025,281724000000,14.932156,87831000000,193893000000,68.823742
10,2026,331839000000,17.788687,106374000000,225465000000,67.944093

In [ ]:
operating_expenses = data["facts"]["us-gaap"]["OperatingExpenses"]

In [ ]:
operating_expenses.keys()

dict_keys(['label', 'description', 'units'])

In [ ]:
operating_expenses_data = operating_expenses["units"]["USD"]

In [ ]:
operating_expenses_df = pd.DataFrame(operating_expenses_data)

In [ ]:
operating_expenses_df.tail(10)

,start,end,val,accn,fy,fp,form,filed,frame
48,2024-07-01,2025-03-31,47261000000,0001193125-26-191507,2026,Q3,10-Q,2026-04-29,NaN
49,2025-01-01,2025-03-31,16147000000,0001193125-26-191507,2026,Q3,10-Q,2026-04-29,CY2025Q1
50,2024-07-01,2025-06-30,65365000000,0000950170-25-100235,2025,FY,10-K,2025-07-30,NaN
51,2024-07-01,2025-06-30,65365000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2025
52,2025-07-01,2025-09-30,15669000000,0001193125-25-256321,2026,Q1,10-Q,2025-10-29,CY2025Q3
53,2025-07-01,2025-12-31,32689000000,0001193125-26-027207,2026,Q2,10-Q,2026-01-28,NaN
54,2025-10-01,2025-12-31,17020000000,0001193125-26-027207,2026,Q2,10-Q,2026-01-28,CY2025Q4
55,2025-07-01,2026-03-31,50349000000,0001193125-26-191507,2026,Q3,10-Q,2026-04-29,NaN
56,2026-01-01,2026-03-31,17660000000,0001193125-26-191507,2026,Q3,10-Q,2026-04-29,CY2026Q1
57,2025-07-01,2026-06-30,70228000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2026

In [ ]:
operating_expenses_df["start"] = pd.to_datetime(operating_expenses_df["start"])
operating_expenses_df["end"] = pd.to_datetime(operating_expenses_df["end"])

operating_expenses_df["duration"] = (
    operating_expenses_df["end"] - operating_expenses_df["start"]
)

In [ ]:
annual_operating_expenses = operating_expenses_df[
    (operating_expenses_df["duration"] >= pd.Timedelta(days=350)) &
    (operating_expenses_df["duration"] <= pd.Timedelta(days=380))
]

In [ ]:
annual_operating_expenses

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2010-07-01,2011-06-30,27205000000,0001193125-13-310206,2013,FY,10-K,2013-07-30,NaN,364 days
1,2010-07-01,2011-06-30,27205000000,0001193125-13-455144,2013,FY,8-K,2013-11-26,CY2011,364 days
7,2011-07-01,2012-06-30,34430000000,0001193125-13-310206,2013,FY,10-K,2013-07-30,NaN,365 days
8,2011-07-01,2012-06-30,34430000000,0001193125-13-455144,2013,FY,8-K,2013-11-26,NaN,365 days
9,2011-07-01,2012-06-30,34430000000,0001193125-14-289961,2014,FY,10-K,2014-07-31,CY2012,365 days
20,2012-07-01,2013-06-30,30836000000,0001193125-13-310206,2013,FY,10-K,2013-07-30,NaN,364 days
21,2012-07-01,2013-06-30,30836000000,0001193125-13-455144,2013,FY,8-K,2013-11-26,NaN,364 days
22,2012-07-01,2013-06-30,30836000000,0001193125-14-289961,2014,FY,10-K,2014-07-31,NaN,364 days
23,2012-07-01,2013-06-30,30700000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2013,364 days
34,2013-07-01,2014-06-30,32140000000,0001193125-14-289961,2014,FY,10-K,2014-07-31,NaN,364 days
35,2013-07-01,2014-06-30,31996000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2014,364 days
41,2014-07-01,2015-06-30,42381000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2015,364 days
42,2022-07-01,2023-06-30,57529000000,0000950170-25-100235,2025,FY,10-K,2025-07-30,CY2023,364 days
43,2023-07-01,2024-06-30,61575000000,0000950170-25-100235,2025,FY,10-K,2025-07-30,NaN,365 days
44,2023-07-01,2024-06-30,61575000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2024,365 days
50,2024-07-01,2025-06-30,65365000000,0000950170-25-100235,2025,FY,10-K,2025-07-30,NaN,364 days
51,2024-07-01,2025-06-30,65365000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2025,364 days
57,2025-07-01,2026-06-30,70228000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_operating_expenses_10k = annual_operating_expenses[
    annual_operating_expenses["form"] == "10-K"
].copy()

In [ ]:
annual_operating_expenses_10k = annual_operating_expenses_10k.sort_values("filed")

In [ ]:
annual_operating_expenses_10k = annual_operating_expenses_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_operating_expenses_10k

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2010-07-01,2011-06-30,27205000000,0001193125-13-310206,2013,FY,10-K,2013-07-30,NaN,364 days
9,2011-07-01,2012-06-30,34430000000,0001193125-14-289961,2014,FY,10-K,2014-07-31,CY2012,365 days
23,2012-07-01,2013-06-30,30700000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2013,364 days
35,2013-07-01,2014-06-30,31996000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2014,364 days
41,2014-07-01,2015-06-30,42381000000,0001193125-15-272806,2015,FY,10-K,2015-07-31,CY2015,364 days
42,2022-07-01,2023-06-30,57529000000,0000950170-25-100235,2025,FY,10-K,2025-07-30,CY2023,364 days
44,2023-07-01,2024-06-30,61575000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2024,365 days
51,2024-07-01,2025-06-30,65365000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2025,364 days
57,2025-07-01,2026-06-30,70228000000,0001193125-26-323660,2026,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
operating_expense_concepts = [
    key for key in data["facts"]["us-gaap"].keys()
    if "OperatingExpense" in key
]

operating_expense_concepts

['OperatingExpenses']

In [ ]:
expense_concepts = [
    key for key in data["facts"]["us-gaap"].keys()
    if "Expense" in key
]

expense_concepts

['AdvertisingExpense',
 'AllocatedShareBasedCompensationExpense',
 'CostsAndExpenses',
 'CurrentFederalTaxExpenseBenefit',
 'CurrentForeignTaxExpenseBenefit',
 'CurrentIncomeTaxExpenseBenefit',
 'CurrentStateAndLocalTaxExpenseBenefit',
 'DeferredFederalIncomeTaxExpenseBenefit',
 'DeferredFederalStateAndLocalTaxExpenseBenefit',
 'DeferredForeignIncomeTaxExpenseBenefit',
 'DeferredIncomeTaxExpenseBenefit',
 'DeferredStateAndLocalIncomeTaxExpenseBenefit',
 'DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost',
 'DeferredTaxAssetsTaxDeferredExpenseOther',
 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsImpairmentLosses',
 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsOther',
 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsRestructuringCharges',
 'EffectiveIncomeTaxRateReconciliationNondeductibleExpense',
 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost',
 'EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense',
 'FinanceLeaseInterestExpense',
 'FiniteLivedIntangibleAssetsAmortizationExpense',
 'FiniteLivedIntangibleAssetsAmortizationExpenseAfterYearFive',
 'FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths',
 'FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear',
 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFive',
 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFour',
 'FiniteLivedIntangibleAssetsAmortizationExpenseYearThree',
 'FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo',
 'FutureAmortizationExpenseAfterYearFive',
 'FutureAmortizationExpenseYearFive',
 'FutureAmortizationExpenseYearFour',
 'FutureAmortizationExpenseYearOne',
 'FutureAmortizationExpenseYearThree',
 'FutureAmortizationExpenseYearTwo',
 'GeneralAndAdministrativeExpense',
 'IncomeTaxExpenseBenefit',
 'InterestExpense',
 'LeaseAndRentalExpense',
 'NonoperatingIncomeExpense',
 'OperatingExpenses',
 'OtherNonoperatingIncomeExpense',
 'ResearchAndDevelopmentExpense',
 'SellingAndMarketingExpense',
 'TaxCutsAndJobsActOf2017IncomeTaxExpenseBenefit',
 'TaxCutsAndJobsActOf2017MeasurementPeriodAdjustmentIncomeTaxExpenseBenefit',
 'UnrecognizedTaxBenefitsIncomeTaxPenaltiesAndInterestExpense',
 'InterestExpenseNonoperating',
 'IncomeTaxReconciliationIncomeTaxExpenseBenefitAtFederalStatutoryIncomeTaxRate']

In [ ]:
for concept in [
    "ResearchAndDevelopmentExpense",
    "SellingAndMarketingExpense",
    "GeneralAndAdministrativeExpense"
]:
    df = pd.DataFrame(
        data["facts"]["us-gaap"][concept]["units"]["USD"]
    )
    df["end"] = pd.to_datetime(df["end"])

    print(concept, "→", df["end"].min(), "to", df["end"].max())

ResearchAndDevelopmentExpense → 2008-06-30 00:00:00 to 2026-06-30 00:00:00
SellingAndMarketingExpense → 2008-06-30 00:00:00 to 2026-06-30 00:00:00
GeneralAndAdministrativeExpense → 2008-06-30 00:00:00 to 2026-06-30 00:00:00

In [ ]:
rd_expense = data["facts"]["us-gaap"]["ResearchAndDevelopmentExpense"]["units"]["USD"]

rd_df = pd.DataFrame(rd_expense)

rd_df["start"] = pd.to_datetime(rd_df["start"])
rd_df["end"] = pd.to_datetime(rd_df["end"])

rd_df["duration"] = rd_df["end"] - rd_df["start"]

In [ ]:
rd_df.tail(10)

,start,end,val,accn,fy,fp,form,filed,frame,duration
220,2025-01-01,2025-03-31,8198000000,0000950170-25-061046,2025.0,Q3,10-Q,2025-04-30,NaN,89 days
221,2025-01-01,2025-03-31,8198000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,CY2025Q1,89 days
222,2024-07-01,2025-06-30,32488000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,NaN,364 days
223,2024-07-01,2025-06-30,32488000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
224,2025-07-01,2025-09-30,8146000000,0001193125-25-256321,2026.0,Q1,10-Q,2025-10-29,CY2025Q3,91 days
225,2025-07-01,2025-12-31,16650000000,0001193125-26-027207,2026.0,Q2,10-Q,2026-01-28,NaN,183 days
226,2025-10-01,2025-12-31,8504000000,0001193125-26-027207,2026.0,Q2,10-Q,2026-01-28,CY2025Q4,91 days
227,2025-07-01,2026-03-31,25565000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,NaN,273 days
228,2026-01-01,2026-03-31,8915000000,0001193125-26-191507,2026.0,Q3,10-Q,2026-04-29,CY2026Q1,89 days
229,2025-07-01,2026-06-30,35562000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_rd = rd_df[
    (rd_df["duration"] >= pd.Timedelta(days=350)) &
    (rd_df["duration"] <= pd.Timedelta(days=380))
]

annual_rd_10k = annual_rd[
    annual_rd["form"] == "10-K"
].copy()

In [ ]:
annual_rd_10k = annual_rd_10k.sort_values("filed")

annual_rd_10k = annual_rd_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_rd_10k

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2007-07-01,2008-06-30,8164000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008,365 days
7,2008-07-01,2009-06-30,9010000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2009,364 days
20,2009-07-01,2010-06-30,8714000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2010,364 days
33,2010-07-01,2011-06-30,9043000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
48,2011-07-01,2012-06-30,9811000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2012,365 days
62,2012-07-01,2013-06-30,10411000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
77,2013-07-01,2014-06-30,11381000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,CY2014,364 days
91,2014-07-01,2015-06-30,12046000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2015,364 days
104,2015-07-01,2016-06-30,11988000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016,365 days
117,2016-07-01,2017-06-30,13037000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,CY2017,364 days
130,2017-07-01,2018-06-30,14726000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,CY2018,364 days
143,2018-07-01,2019-06-30,16876000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,CY2019,364 days
156,2019-07-01,2020-06-30,19269000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,CY2020,365 days
169,2020-07-01,2021-06-30,20716000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,CY2021,364 days
182,2021-07-01,2022-06-30,24512000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
197,2022-07-01,2023-06-30,27195000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,CY2023,364 days
223,2024-07-01,2025-06-30,32488000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
211,2023-07-01,2024-06-30,29510000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2024,365 days
229,2025-07-01,2026-06-30,35562000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_rd = rd_df[
    (rd_df["duration"] >= pd.Timedelta(days=350)) &
    (rd_df["duration"] <= pd.Timedelta(days=380))
]

annual_rd_10k = annual_rd[
    annual_rd["form"] == "10-K"
].copy()

In [ ]:
annual_rd_10k = annual_rd_10k.sort_values("filed")

annual_rd_10k = annual_rd_10k.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_rd_10k

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2007-07-01,2008-06-30,8164000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008,365 days
7,2008-07-01,2009-06-30,9010000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2009,364 days
20,2009-07-01,2010-06-30,8714000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2010,364 days
33,2010-07-01,2011-06-30,9043000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
48,2011-07-01,2012-06-30,9811000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2012,365 days
62,2012-07-01,2013-06-30,10411000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
77,2013-07-01,2014-06-30,11381000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,CY2014,364 days
91,2014-07-01,2015-06-30,12046000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2015,364 days
104,2015-07-01,2016-06-30,11988000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016,365 days
117,2016-07-01,2017-06-30,13037000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,CY2017,364 days
130,2017-07-01,2018-06-30,14726000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,CY2018,364 days
143,2018-07-01,2019-06-30,16876000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,CY2019,364 days
156,2019-07-01,2020-06-30,19269000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,CY2020,365 days
169,2020-07-01,2021-06-30,20716000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,CY2021,364 days
182,2021-07-01,2022-06-30,24512000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
197,2022-07-01,2023-06-30,27195000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,CY2023,364 days
223,2024-07-01,2025-06-30,32488000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
211,2023-07-01,2024-06-30,29510000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2024,365 days
229,2025-07-01,2026-06-30,35562000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_rd_10k

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2007-07-01,2008-06-30,8164000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008,365 days
7,2008-07-01,2009-06-30,9010000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2009,364 days
20,2009-07-01,2010-06-30,8714000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2010,364 days
33,2010-07-01,2011-06-30,9043000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
48,2011-07-01,2012-06-30,9811000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2012,365 days
62,2012-07-01,2013-06-30,10411000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
77,2013-07-01,2014-06-30,11381000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,CY2014,364 days
91,2014-07-01,2015-06-30,12046000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2015,364 days
104,2015-07-01,2016-06-30,11988000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016,365 days
117,2016-07-01,2017-06-30,13037000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,CY2017,364 days
130,2017-07-01,2018-06-30,14726000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,CY2018,364 days
143,2018-07-01,2019-06-30,16876000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,CY2019,364 days
156,2019-07-01,2020-06-30,19269000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,CY2020,365 days
169,2020-07-01,2021-06-30,20716000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,CY2021,364 days
182,2021-07-01,2022-06-30,24512000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
197,2022-07-01,2023-06-30,27195000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,CY2023,364 days
223,2024-07-01,2025-06-30,32488000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
211,2023-07-01,2024-06-30,29510000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2024,365 days
229,2025-07-01,2026-06-30,35562000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_rd_10k["fiscal_year"] = annual_rd_10k["end"].dt.year

rd_final = annual_rd_10k[
    ["fiscal_year", "val"]
].copy()

rd_final = rd_final.rename(
    columns={"val": "rd_expense"}
)

rd_final = rd_final[
    (rd_final["fiscal_year"] >= 2016) &
    (rd_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
rd_final

    fiscal_year   rd_expense
0          2016  11988000000
1          2017  13037000000
2          2018  14726000000
3          2019  16876000000
4          2020  19269000000
5          2021  20716000000
6          2022  24512000000
7          2023  27195000000
8          2024  29510000000
9          2025  32488000000
10         2026  35562000000

In [ ]:
sm_expense = data["facts"]["us-gaap"]["SellingAndMarketingExpense"]["units"]["USD"]

sm_df = pd.DataFrame(sm_expense)

sm_df["start"] = pd.to_datetime(sm_df["start"])
sm_df["end"] = pd.to_datetime(sm_df["end"])

sm_df["duration"] = sm_df["end"] - sm_df["start"]

In [ ]:
annual_sm = sm_df[
    (sm_df["duration"] >= pd.Timedelta(days=350)) &
    (sm_df["duration"] <= pd.Timedelta(days=380)) &
    (sm_df["form"] == "10-K")
].copy()

annual_sm = annual_sm.sort_values("filed")

annual_sm = annual_sm.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_sm["fiscal_year"] = annual_sm["end"].dt.year

sm_final = annual_sm[
    ["fiscal_year", "val"]
].copy()

sm_final = sm_final.rename(
    columns={"val": "sm_expense"}
)

sm_final = sm_final[
    (sm_final["fiscal_year"] >= 2016) &
    (sm_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
sm_final

    fiscal_year   sm_expense
0          2016  14635000000
1          2017  15461000000
2          2018  17469000000
3          2019  18213000000
4          2020  19598000000
5          2021  20117000000
6          2022  21825000000
7          2023  22759000000
8          2024  24456000000
9          2025  25654000000
10         2026  26710000000

In [ ]:
ga_expense = data["facts"]["us-gaap"]["GeneralAndAdministrativeExpense"]["units"]["USD"]

ga_df = pd.DataFrame(ga_expense)

ga_df["start"] = pd.to_datetime(ga_df["start"])
ga_df["end"] = pd.to_datetime(ga_df["end"])

ga_df["duration"] = ga_df["end"] - ga_df["start"]

In [ ]:
annual_ga = ga_df[
    (ga_df["duration"] >= pd.Timedelta(days=350)) &
    (ga_df["duration"] <= pd.Timedelta(days=380)) &
    (ga_df["form"] == "10-K")
].copy()

annual_ga = annual_ga.sort_values("filed")

annual_ga = annual_ga.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_ga["fiscal_year"] = annual_ga["end"].dt.year

ga_final = annual_ga[
    ["fiscal_year", "val"]
].copy()

ga_final = ga_final.rename(
    columns={"val": "ga_expense"}
)

ga_final = ga_final[
    (ga_final["fiscal_year"] >= 2016) &
    (ga_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
ga_final

    fiscal_year  ga_expense
0          2016  4563000000
1          2017  4481000000
2          2018  4754000000
3          2019  4885000000
4          2020  5111000000
5          2021  5107000000
6          2022  5900000000
7          2023  7575000000
8          2024  7609000000
9          2025  7223000000
10         2026  7956000000

In [ ]:
financials_opex = financials.copy()

In [ ]:
financials_opex = financials_opex.merge(
    rd_final,
    on="fiscal_year",
    how="left"
)

financials_opex = financials_opex.merge(
    sm_final,
    on="fiscal_year",
    how="left"
)

financials_opex = financials_opex.merge(
    ga_final,
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_opex["reconstructed_opex"] = (
    financials_opex["rd_expense"]
    + financials_opex["sm_expense"]
    + financials_opex["ga_expense"]
)

In [ ]:
financials_opex[
    [
        "fiscal_year",
        "rd_expense",
        "sm_expense",
        "ga_expense",
        "reconstructed_opex"
    ]
]

    fiscal_year   rd_expense   sm_expense  ga_expense  reconstructed_opex
0          2016  11988000000  14635000000  4563000000         31186000000
1          2017  13037000000  15461000000  4481000000         32979000000
2          2018  14726000000  17469000000  4754000000         36949000000
3          2019  16876000000  18213000000  4885000000         39974000000
4          2020  19269000000  19598000000  5111000000         43978000000
5          2021  20716000000  20117000000  5107000000         45940000000
6          2022  24512000000  21825000000  5900000000         52237000000
7          2023  27195000000  22759000000  7575000000         57529000000
8          2024  29510000000  24456000000  7609000000         61575000000
9          2025  32488000000  25654000000  7223000000         65365000000
10         2026  35562000000  26710000000  7956000000         70228000000

In [ ]:
reported_opex = annual_operating_expenses_10k.copy()

reported_opex["fiscal_year"] = reported_opex["end"].dt.year

reported_opex = reported_opex[
    ["fiscal_year", "val"]
].copy()

reported_opex = reported_opex.rename(
    columns={"val": "reported_opex"}
)

reported_opex = reported_opex[
    (reported_opex["fiscal_year"] >= 2016) &
    (reported_opex["fiscal_year"] <= 2026)
]

In [ ]:
opex_check = financials_opex.merge(
    reported_opex,
    on="fiscal_year",
    how="left"
)

In [ ]:
opex_check["difference"] = (
    opex_check["reconstructed_opex"]
    - opex_check["reported_opex"]
)

In [ ]:
opex_check[
    [
        "fiscal_year",
        "reconstructed_opex",
        "reported_opex",
        "difference"
    ]
]

    fiscal_year  reconstructed_opex  reported_opex  difference
0          2016         31186000000            NaN         NaN
1          2017         32979000000            NaN         NaN
2          2018         36949000000            NaN         NaN
3          2019         39974000000            NaN         NaN
4          2020         43978000000            NaN         NaN
5          2021         45940000000            NaN         NaN
6          2022         52237000000            NaN         NaN
7          2023         57529000000   5.752900e+10         0.0
8          2024         61575000000   6.157500e+10         0.0
9          2025         65365000000   6.536500e+10         0.0
10         2026         70228000000   7.022800e+10         0.0

In [ ]:
financials_opex["operating_income"] = (
    financials_opex["gross_profit"]
    - financials_opex["reconstructed_opex"]
)

In [ ]:
financials_opex["operating_margin"] = (
    financials_opex["operating_income"]
    / financials_opex["revenue"]
    * 100
)

In [ ]:
financials_opex[
    [
        "fiscal_year",
        "revenue",
        "gross_profit",
        "reconstructed_opex",
        "operating_income",
        "operating_margin"
    ]
]

,fiscal_year,revenue,gross_profit,reconstructed_opex,operating_income,operating_margin
0,2016,91154000000,58374000000,31186000000,27188000000,29.826448
1,2017,96571000000,62310000000,32979000000,29331000000,30.372472
2,2018,110360000000,72007000000,36949000000,35058000000,31.766945
3,2019,125843000000,82933000000,39974000000,42959000000,34.136980
4,2020,143015000000,96937000000,43978000000,52959000000,37.030381
5,2021,168088000000,115856000000,45940000000,69916000000,41.594879
6,2022,198270000000,135620000000,52237000000,83383000000,42.055278
7,2023,211915000000,146052000000,57529000000,88523000000,41.772881
8,2024,245122000000,171008000000,61575000000,109433000000,44.644300
9,2025,281724000000,193893000000,65365000000,128528000000,45.621956
10,2026,331839000000,225465000000,70228000000,155237000000,46.780818

In [ ]:
net_income = data["facts"]["us-gaap"]["NetIncomeLoss"]["units"]["USD"]

net_income_df = pd.DataFrame(net_income)

net_income_df["start"] = pd.to_datetime(net_income_df["start"])
net_income_df["end"] = pd.to_datetime(net_income_df["end"])

net_income_df["duration"] = (
    net_income_df["end"] - net_income_df["start"]
)

In [ ]:
annual_net_income = net_income_df[
    (net_income_df["duration"] >= pd.Timedelta(days=350)) &
    (net_income_df["duration"] <= pd.Timedelta(days=380)) &
    (net_income_df["form"] == "10-K")
].copy()

annual_net_income = annual_net_income.sort_values("filed")

annual_net_income = annual_net_income.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_net_income["fiscal_year"] = (
    annual_net_income["end"].dt.year
)

net_income_final = annual_net_income[
    ["fiscal_year", "val"]
].copy()

net_income_final = net_income_final.rename(
    columns={"val": "net_income"}
)

net_income_final = net_income_final[
    (net_income_final["fiscal_year"] >= 2016) &
    (net_income_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
net_income_final

    fiscal_year    net_income
0          2016   20539000000
1          2017   25489000000
2          2018   16571000000
3          2019   39240000000
4          2020   44281000000
5          2021   61271000000
6          2022   72738000000
7          2023   72361000000
8          2024   88136000000
9          2025  101832000000
10         2026  133749000000

In [ ]:
financials_final = financials_opex.merge(
    net_income_final,
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_final["net_profit_margin"] = (
    financials_final["net_income"]
    / financials_final["revenue"]
    * 100
)

In [ ]:
financials_final[
    [
        "fiscal_year",
        "revenue",
        "revenue_growth",
        "gross_margin",
        "operating_margin",
        "net_income",
        "net_profit_margin"
    ]
]

,fiscal_year,revenue,revenue_growth,gross_margin,operating_margin,net_income,net_profit_margin
0,2016,91154000000,NaN,64.038879,29.826448,20539000000,22.532198
1,2017,96571000000,5.942690,64.522476,30.372472,25489000000,26.394052
2,2018,110360000000,14.278614,65.247372,31.766945,16571000000,15.015404
3,2019,125843000000,14.029540,65.901957,34.136980,39240000000,31.181711
4,2020,143015000000,13.645574,67.781002,37.030381,44281000000,30.962486
5,2021,168088000000,17.531727,68.925801,41.594879,61271000000,36.451740
6,2022,198270000000,17.956071,68.401674,42.055278,72738000000,36.686337
7,2023,211915000000,6.882030,68.920086,41.772881,72361000000,34.146238
8,2024,245122000000,15.669962,69.764444,44.644300,88136000000,35.955973
9,2025,281724000000,14.932156,68.823742,45.621956,101832000000,36.146015
10,2026,331839000000,17.788687,67.944093,46.780818,133749000000,40.305389

In [ ]:
data["facts"]["us-gaap"]["NetCashProvidedByUsedInOperatingActivities"]

{'label': 'Net Cash Provided by (Used in) Operating Activities',
 'description': 'Amount of cash inflow (outflow) from operating activities, including discontinued operations. Operating activity cash flows include transactions, adjustments, and changes in value not defined as investing or financing activities.',
 'units': {'USD': [{'start': '2007-07-01',
    'end': '2008-06-30',
    'val': 21612000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30',
    'frame': 'CY2008'},
   {'start': '2008-07-01',
    'end': '2008-09-30',
    'val': 3370000000,
    'accn': '0001193125-09-212454',
    'fy': 2010,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2009-10-23',
    'frame': 'CY2008Q3'},
   {'start': '2008-07-01',
    'end': '2008-12-31',
    'val': 9152000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2008-10-01',
    'end': '2008-12-31',
    'val': 5782000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28',
    'frame': 'CY2008Q4'},
   {'start': '2008-07-01',
    'end': '2009-03-31',
    'val': 15196000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2009-01-01',
    'end': '2009-03-31',
    'val': 6044000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22',
    'frame': 'CY2009Q1'},
   {'start': '2008-07-01',
    'end': '2009-06-30',
    'val': 19037000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30'},
   {'start': '2008-07-01',
    'end': '2009-06-30',
    'val': 19037000000,
    'accn': '0001193125-11-200680',
    'fy': 2011,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2011-07-28',
    'frame': 'CY2009'},
   {'start': '2009-07-01',
    'end': '2009-09-30',
    'val': 6107000000,
    'accn': '0001193125-09-212454',
    'fy': 2010,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2009-10-23'},
   {'start': '2009-07-01',
    'end': '2009-09-30',
    'val': 6107000000,
    'accn': '0001193125-10-239825',
    'fy': 2011,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2010-10-28',
    'frame': 'CY2009Q3'},
   {'start': '2009-07-01',
    'end': '2009-12-31',
    'val': 11076000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2009-07-01',
    'end': '2009-12-31',
    'val': 11076000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27'},
   {'start': '2009-10-01',
    'end': '2009-12-31',
    'val': 4969000000,
    'accn': '0001193125-10-015598',
    'fy': 2010,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2010-01-28'},
   {'start': '2009-10-01',
    'end': '2009-12-31',
    'val': 4969000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27',
    'frame': 'CY2009Q4'},
   {'start': '2009-07-01',
    'end': '2010-03-31',
    'val': 18469000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2009-07-01',
    'end': '2010-03-31',
    'val': 18469000000,
    'accn': '0001193125-11-115186',
    'fy': 2011,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2011-04-28'},
   {'start': '2010-01-01',
    'end': '2010-03-31',
    'val': 7393000000,
    'accn': '0001193125-10-090116',
    'fy': 2010,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2010-04-22'},
   {'start': '2010-01-01',
    'end': '2010-03-31',
    'val': 7393000000,
    'accn': '0001193125-11-115186',
    'fy': 2011,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2011-04-28',
    'frame': 'CY2010Q1'},
   {'start': '2009-07-01',
    'end': '2010-06-30',
    'val': 24073000000,
    'accn': '0001193125-10-171791',
    'fy': 2010,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2010-07-30'},
   {'start': '2009-07-01',
    'end': '2010-06-30',
    'val': 24073000000,
    'accn': '0001193125-11-200680',
    'fy': 2011,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2011-07-28'},
   {'start': '2009-07-01',
    'end': '2010-06-30',
    'val': 24073000000,
    'accn': '0001193125-12-316848',
    'fy': 2012,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2012-07-26',
    'frame': 'CY2010'},
   {'start': '2010-07-01',
    'end': '2010-09-30',
    'val': 8194000000,
    'accn': '0001193125-10-239825',
    'fy': 2011,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2010-10-28'},
   {'start': '2010-07-01',
    'end': '2010-09-30',
    'val': 8194000000,
    'accn': '0001193125-11-276022',
    'fy': 2012,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2011-10-20',
    'frame': 'CY2010Q3'},
   {'start': '2010-07-01',
    'end': '2010-12-31',
    'val': 12380000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27'},
   {'start': '2010-07-01',
    'end': '2010-12-31',
    'val': 12380000000,
    'accn': '0001193125-12-026864',
    'fy': 2012,
    'fp': 'Q2',
    'form': '10-Q/A',
    'filed': '2012-01-27'},
   {'start': '2010-10-01',
    'end': '2010-12-31',
    'val': 4186000000,
    'accn': '0001193125-11-015947',
    'fy': 2011,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2011-01-27'},
   {'start': '2010-10-01',
    'end': '2010-12-31',
    'val': 4186000000,
    'accn': '0001193125-12-026864',
    'fy': 2012,
    'fp': 'Q2',
    'form': '10-Q/A',
    'filed': '2012-01-27',
    'frame': 'CY2010Q4'},
   {'start': '2010-07-01',
    'end': '2011-03-31',
    'val': 21052000000,
    'accn': '0001193125-11-115186',
    'fy': 2011,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2011-04-28'},
   {'start': '2010-07-01',
    'end': '2011-03-31',
    'val': 21052000000,
    'accn': '0001193125-12-170665',
    'fy': 2012,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2012-04-19'},
   {'start': '2011-01-01',
    'end': '2011-03-31',
    'val': 8672000000,
    'accn': '0001193125-11-115186',
    'fy': 2011,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2011-04-28'},
   {'start': '2011-01-01',
    'end': '2011-03-31',
    'val': 8672000000,
    'accn': '0001193125-12-170665',
    'fy': 2012,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2012-04-19',
    'frame': 'CY2011Q1'},
   {'start': '2010-07-01',
    'end': '2011-06-30',
    'val': 26994000000,
    'accn': '0001193125-11-200680',
    'fy': 2011,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2011-07-28'},
   {'start': '2010-07-01',
    'end': '2011-06-30',
    'val': 26994000000,
    'accn': '0001193125-12-316848',
    'fy': 2012,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2012-07-26'},
   {'start': '2010-07-01',
    'end': '2011-06-30',
    'val': 26994000000,
    'accn': '0001193125-13-310206',
    'fy': 2013,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2013-07-30',
    'frame': 'CY2011'},
   {'start': '2011-07-01',
    'end': '2011-09-30',
    'val': 8493000000,
    'accn': '0001193125-11-276022',
    'fy': 2012,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2011-10-20'},
   {'start': '2011-07-01',
    'end': '2011-09-30',
    'val': 8493000000,
    'accn': '0001193125-12-427209',
    'fy': 2013,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2012-10-18',
    'frame': 'CY2011Q3'},
   {'start': '2011-07-01',
    'end': '2011-12-31',
    'val': 14355000000,
    'accn': '0001193125-12-026864',
    'fy': 2012,
    'fp': 'Q2',
    'form': '10-Q/A',
    'filed': '2012-01-27'},
   {'start': '2011-07-01',
    'end': '2011-12-31',
    'val': 14355000000,
    'accn': '0001193125-13-022207',
    'fy': 2013,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2013-01-24'},
   {'start': '2011-10-01',
    'end': '2011-12-31',
    'val': 5862000000,
    'accn': '0001193125-12-026864',
    'fy': 2012,
    'fp': 'Q2',
    'form': '10-Q/A',
    'filed': '2012-01-27'},
   {'start': '2011-10-01',
    'end': '2011-12-31',
    'val': 5862000000,
    'accn': '0001193125-13-022207',
    'fy': 2013,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2013-01-24',
    'frame': 'CY2011Q4'},
   {'start': '2011-07-01',
    'end': '2012-03-31',
    'val': 23949000000,
    'accn': '0001193125-12-170665',
    'fy': 2012,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2012-04-19'},
   {'start': '2011-07-01',
    'end': '2012-03-31',
    'val': 23949000000,
    'accn': '0001193125-13-160748',
    'fy': 2013,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2013-04-18'},
   {'start': '2012-01-01',
    'end': '2012-03-31',
    'val': 9594000000,
    'accn': '0001193125-12-170665',
    'fy': 2012,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2012-04-19'},
   {'start': '2012-01-01',
    'end': '2012-03-31',
    'val': 9594000000,
    'accn': '0001193125-13-160748',
    'fy': 2013,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2013-04-18',
    'frame': 'CY2012Q1'},
   {'start': '2011-07-01',
    'end': '2012-06-30',
    'val': 31626000000,
    'accn': '0001193125-12-316848',
    'fy': 2012,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2012-07-26'},
   {'start': '2011-07-01',
    'end': '2012-06-30',
    'val': 31626000000,
    'accn': '0001193125-13-310206',
    'fy': 2013,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2013-07-30',
    'frame': 'CY2012'},
   {'start': '2012-07-01',
    'end': '2012-09-30',
    'val': 8484000000,
    'accn': '0001193125-12-427209',
    'fy': 2013,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2012-10-18',
    'frame': 'CY2012Q3'},
   {'start': '2012-07-01',
    'end': '2012-12-31',
    'val': 13264000000,
    'accn': '0001193125-13-022207',
    'fy': 2013,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2013-01-24'},
   {'start': '2012-10-01',
    'end': '2012-12-31',
    'val': 4780000000,
    'accn': '0001193125-13-022207',
    'fy': 2013,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2013-01-24',
    'frame': 'CY2012Q4'},
   {'start': '2012-07-01',
    'end': '2013-03-31',
    'val': 22930000000,
    'accn': '0001193125-13-160748',
    'fy': 2013,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2013-04-18'},
   {'start': '2013-01-01',
    'end': '2013-03-31',
    'val': 9666000000,
    'accn': '0001193125-13-160748',
    'fy': 2013,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2013-04-18',
    'frame': 'CY2013Q1'},
   {'start': '2012-07-01',
    'end': '2013-06-30',
    'val': 28833000000,
    'accn': '0001193125-13-310206',
    'fy': 2013,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2013-07-30',
    'frame': 'CY2013'},
   {'start': '2015-07-01',
    'end': '2016-06-30',
    'val': 33325000000,
    'accn': '0001564590-18-019062',
    'fy': 2018,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2018-08-03',
    'frame': 'CY2016'},
   {'start': '2016-07-01',
    'end': '2016-12-31',
    'val': 17842000000,
    'accn': '0001564590-18-001129',
    'fy': 2018,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2018-01-31'},
   {'start': '2016-10-01',
    'end': '2016-12-31',
    'val': 6293000000,
    'accn': '0001564590-18-001129',
    'fy': 2018,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2018-01-31',
    'frame': 'CY2016Q4'},
   {'start': '2016-07-01',
    'end': '2017-03-31',
    'val': 28502000000,
    'accn': '0001564590-18-009307',
    'fy': 2018,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2018-04-26'},
   {'start': '2017-01-01',
    'end': '2017-03-31',
    'val': 10660000000,
    'accn': '0001564590-18-009307',
    'fy': 2018,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2018-04-26',
    'frame': 'CY2017Q1'},
   {'start': '2016-07-01',
    'end': '2017-06-30',
    'val': 39507000000,
    'accn': '0001564590-18-019062',
    'fy': 2018,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2018-08-03'},
   {'start': '2016-07-01',
    'end': '2017-06-30',
    'val': 39507000000,
    'accn': '0001564590-19-027952',
    'fy': 2019,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2019-08-01',
    'frame': 'CY2017'},
   {'start': '2017-07-01',
    'end': '2017-09-30',
    'val': 12440000000,
    'accn': '0001564590-18-024893',
    'fy': 2019,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2018-10-24',
    'frame': 'CY2017Q3'},
   {'start': '2017-07-01',
    'end': '2017-12-31',
    'val': 20315000000,
    'accn': '0001564590-18-001129',
    'fy': 2018,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2018-01-31'},
   {'start': '2017-07-01',
    'end': '2017-12-31',
    'val': 20315000000,
    'accn': '0001564590-19-001392',
    'fy': 2019,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2019-01-30'},
   {'start': '2017-10-01',
    'end': '2017-12-31',
    'val': 7875000000,
    'accn': '0001564590-18-001129',
    'fy': 2018,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2018-01-31'},
   {'start': '2017-10-01',
    'end': '2017-12-31',
    'val': 7875000000,
    'accn': '0001564590-19-001392',
    'fy': 2019,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2019-01-30',
    'frame': 'CY2017Q4'},
   {'start': '2017-07-01',
    'end': '2018-03-31',
    'val': 32466000000,
    'accn': '0001564590-18-009307',
    'fy': 2018,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2018-04-26'},
   {'start': '2017-07-01',
    'end': '2018-03-31',
    'val': 32466000000,
    'accn': '0001564590-19-012709',
    'fy': 2019,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2019-04-24'},
   {'start': '2018-01-01',
    'end': '2018-03-31',
    'val': 12151000000,
    'accn': '0001564590-18-009307',
    'fy': 2018,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2018-04-26'},
   {'start': '2018-01-01',
    'end': '2018-03-31',
    'val': 12151000000,
    'accn': '0001564590-19-012709',
    'fy': 2019,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2019-04-24',
    'frame': 'CY2018Q1'},
   {'start': '2017-07-01',
    'end': '2018-06-30',
    'val': 43884000000,
    'accn': '0001564590-18-019062',
    'fy': 2018,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2018-08-03'},
   {'start': '2017-07-01',
    'end': '2018-06-30',
    'val': 43884000000,
    'accn': '0001564590-19-027952',
    'fy': 2019,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2019-08-01'},
   {'start': '2017-07-01',
    'end': '2018-06-30',
    'val': 43884000000,
    'accn': '0001564590-20-034944',
    'fy': 2020,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2020-07-30',
    'frame': 'CY2018'},
   {'start': '2018-07-01',
    'end': '2018-09-30',
    'val': 13657000000,
    'accn': '0001564590-18-024893',
    'fy': 2019,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2018-10-24'},
   {'start': '2018-07-01',
    'end': '2018-09-30',
    'val': 13657000000,
    'accn': '0001564590-19-037549',
    'fy': 2020,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2019-10-23',
    'frame': 'CY2018Q3'},
   {'start': '2018-07-01',
    'end': '2018-12-31',
    'val': 22557000000,
    'accn': '0001564590-19-001392',
    'fy': 2019,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2019-01-30'},
   {'start': '2018-07-01',
    'end': '2018-12-31',
    'val': 22557000000,
    'accn': '0001564590-20-002450',
    'fy': 2020,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2020-01-29'},
   {'start': '2018-10-01',
    'end': '2018-12-31',
    'val': 8900000000,
    'accn': '0001564590-19-001392',
    'fy': 2019,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2019-01-30'},
   {'start': '2018-10-01',
    'end': '2018-12-31',
    'val': 8900000000,
    'accn': '0001564590-20-002450',
    'fy': 2020,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2020-01-29',
    'frame': 'CY2018Q4'},
   {'start': '2018-07-01',
    'end': '2019-03-31',
    'val': 36077000000,
    'accn': '0001564590-19-012709',
    'fy': 2019,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2019-04-24'},
   {'start': '2018-07-01',
    'end': '2019-03-31',
    'val': 36077000000,
    'accn': '0001564590-20-019706',
    'fy': 2020,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2020-04-29'},
   {'start': '2019-01-01',
    'end': '2019-03-31',
    'val': 13520000000,
    'accn': '0001564590-19-012709',
    'fy': 2019,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2019-04-24'},
   {'start': '2019-01-01',
    'end': '2019-03-31',
    'val': 13520000000,
    'accn': '0001564590-20-019706',
    'fy': 2020,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2020-04-29',
    'frame': 'CY2019Q1'},
   {'start': '2018-07-01',
    'end': '2019-06-30',
    'val': 52185000000,
    'accn': '0001564590-19-027952',
    'fy': 2019,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2019-08-01'},
   {'start': '2018-07-01',
    'end': '2019-06-30',
    'val': 52185000000,
    'accn': '0001564590-20-034944',
    'fy': 2020,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2020-07-30'},
   {'start': '2018-07-01',
    'end': '2019-06-30',
    'val': 52185000000,
    'accn': '0001564590-21-039151',
    'fy': 2021,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2021-07-29',
    'frame': 'CY2019'},
   {'start': '2019-07-01',
    'end': '2019-09-30',
    'val': 13818000000,
    'accn': '0001564590-19-037549',
    'fy': 2020,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2019-10-23'},
   {'start': '2019-07-01',
    'end': '2019-09-30',
    'val': 13818000000,
    'accn': '0001564590-20-047996',
    'fy': 2021,
    'fp': 'Q1',
    'form': '10-Q',
    'filed': '2020-10-27',
    'frame': 'CY2019Q3'},
   {'start': '2019-07-01',
    'end': '2019-12-31',
    'val': 24498000000,
    'accn': '0001564590-20-002450',
    'fy': 2020,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2020-01-29'},
   {'start': '2019-07-01',
    'end': '2019-12-31',
    'val': 24498000000,
    'accn': '0001564590-21-002316',
    'fy': 2021,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2021-01-26'},
   {'start': '2019-10-01',
    'end': '2019-12-31',
    'val': 10680000000,
    'accn': '0001564590-20-002450',
    'fy': 2020,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2020-01-29'},
   {'start': '2019-10-01',
    'end': '2019-12-31',
    'val': 10680000000,
    'accn': '0001564590-21-002316',
    'fy': 2021,
    'fp': 'Q2',
    'form': '10-Q',
    'filed': '2021-01-26',
    'frame': 'CY2019Q4'},
   {'start': '2019-07-01',
    'end': '2020-03-31',
    'val': 42002000000,
    'accn': '0001564590-20-019706',
    'fy': 2020,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2020-04-29'},
   {'start': '2019-07-01',
    'end': '2020-03-31',
    'val': 42002000000,
    'accn': '0001564590-21-020891',
    'fy': 2021,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2021-04-27'},
   {'start': '2020-01-01',
    'end': '2020-03-31',
    'val': 17504000000,
    'accn': '0001564590-20-019706',
    'fy': 2020,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2020-04-29'},
   {'start': '2020-01-01',
    'end': '2020-03-31',
    'val': 17504000000,
    'accn': '0001564590-21-020891',
    'fy': 2021,
    'fp': 'Q3',
    'form': '10-Q',
    'filed': '2021-04-27',
    'frame': 'CY2020Q1'},
   {'start': '2019-07-01',
    'end': '2020-06-30',
    'val': 60675000000,
    'accn': '0001564590-20-034944',
    'fy': 2020,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2020-07-30'},
   {'start': '2019-07-01',
    'end': '2020-06-30',
    'val': 60675000000,
    'accn': '0001564590-21-039151',
    'fy': 2021,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2021-07-29'},
   {'start': '2019-07-01',
    'end': '2020-06-30',
    'val': 60675000000,
    'accn': '0001564590-22-026876',
    'fy': 2022,
    'fp': 'FY',
    'form': '10-K',
    'filed': '2022-07-28',
    'frame': 'CY2020'},
   {'start': '2020-07-01',
    'end': '2020-09-30',
    'val': 19335000000,
    'accn': '0001564590-20-047996',
    'fy': 2021,
    'fp': 'Q1',
    'form': '10-Q',

In [ ]:
cash_flow = data["facts"]["us-gaap"]["NetCashProvidedByUsedInOperatingActivities"]["units"]["USD"]

cash_flow_df = pd.DataFrame(cash_flow)

cash_flow_df.head()

,start,end,val,accn,fy,fp,form,filed,frame
0,2007-07-01,2008-06-30,21612000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008
1,2008-07-01,2008-09-30,3370000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,CY2008Q3
2,2008-07-01,2008-12-31,9152000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,NaN
3,2008-10-01,2008-12-31,5782000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,CY2008Q4
4,2008-07-01,2009-03-31,15196000000,0001193125-10-090116,2010.0,Q3,10-Q,2010-04-22,NaN

In [ ]:
cash_flow_df["start"] = pd.to_datetime(cash_flow_df["start"])
cash_flow_df["end"] = pd.to_datetime(cash_flow_df["end"])

In [ ]:
cash_flow_df["duration"] = cash_flow_df["end"] - cash_flow_df["start"]

In [ ]:
annual_cash_flow_df = cash_flow_df[
    (cash_flow_df["duration"] >= pd.Timedelta(days=350)) &
    (cash_flow_df["duration"] <= pd.Timedelta(days=380)) &
    (cash_flow_df["form"] == "10-K")
].copy()

In [ ]:
annual_cash_flow_df = annual_cash_flow_df.sort_values("filed")

In [ ]:
annual_cash_flow_df = annual_cash_flow_df.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_cash_flow_df = annual_cash_flow_df.sort_values("filed")

In [ ]:
annual_cash_flow_df = annual_cash_flow_df.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_cash_flow_df["fiscal_year"] = annual_cash_flow_df["end"].dt.year

cash_flow_final = annual_cash_flow_df[
    ["fiscal_year", "val"]
].copy()

cash_flow_final = cash_flow_final.rename(
    columns={"val": "operating_cash_flow"}
)

cash_flow_final = cash_flow_final[
    (cash_flow_final["fiscal_year"] >= 2016) &
    (cash_flow_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
cash_flow_final

    fiscal_year  operating_cash_flow
0          2016          33325000000
1          2017          39507000000
2          2018          43884000000
3          2019          52185000000
4          2020          60675000000
5          2021          76740000000
6          2022          89035000000
7          2023          87582000000
8          2024         118548000000
9          2025         136162000000
10         2026         182935000000

In [ ]:
financials_final = financials_final.merge(
    cash_flow_final,
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_final[
    [
        "fiscal_year",
        "revenue",
        "operating_income",
        "net_income",
        "operating_cash_flow"
    ]
]

,fiscal_year,revenue,operating_income,net_income,operating_cash_flow
0,2016,91154000000,27188000000,20539000000,33325000000
1,2017,96571000000,29331000000,25489000000,39507000000
2,2018,110360000000,35058000000,16571000000,43884000000
3,2019,125843000000,42959000000,39240000000,52185000000
4,2020,143015000000,52959000000,44281000000,60675000000
5,2021,168088000000,69916000000,61271000000,76740000000
6,2022,198270000000,83383000000,72738000000,89035000000
7,2023,211915000000,88523000000,72361000000,87582000000
8,2024,245122000000,109433000000,88136000000,118548000000
9,2025,281724000000,128528000000,101832000000,136162000000
10,2026,331839000000,155237000000,133749000000,182935000000

In [ ]:
data["facts"]["us-gaap"].keys()

dict_keys(['AccountsPayableCurrent', 'AccountsReceivableNet', 'AccountsReceivableNetCurrent', 'AccountsReceivableNetNoncurrent', 'AccruedIncomeTaxesCurrent', 'AccruedIncomeTaxesNoncurrent', 'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', 'AccumulatedOtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossCumulativeChangesInNetGainLossFromCashFlowHedgesEffectNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentNetOfTax', 'AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'AcquiredFiniteLivedIntangibleAssetAmount', 'AcquiredFiniteLivedIntangibleAssetWeightedAverageUsefulLife', 'AdvertisingExpense', 'AllocatedShareBasedCompensationExpense', 'AllowanceForDoubtfulAccountsReceivableCurrent', 'AmortizationOfIntangibleAssets', 'AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount', 'AssetImpairmentCharges', 'Assets', 'AssetsCurrent', 'AssetsFairValueDisclosureRecurring', 'AvailableForSaleDebtSecuritiesAmortizedCostBasis', 'AvailableForSaleSecurities', 'AvailableForSaleSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', 'AvailableForSaleSecuritiesAccumulatedGrossUnrealizedLossBeforeTax', 'AvailableForSaleSecuritiesAmortizedCost', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionFairValue', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThanTwelveMonthsFairValue', 'AvailableForSaleSecuritiesContinuousUnrealizedLossPositionTwelveMonthsOrLongerFairValue', 'AvailableForSaleSecuritiesCurrent', 'AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearFairValue', 'AvailableForSaleSecuritiesDebtSecurities', 'AvailableForSaleSecuritiesGrossRealizedGains', 'AvailableForSaleSecuritiesGrossRealizedLosses', 'AvailableForSaleSecuritiesGrossUnrealizedLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAggregateLosses2', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionAggregateLosses2', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAggregateLosses1', 'AvailableforsaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAggregateLosses2', 'AvailableforsaleSecuritiesGrossUnrealizedGain', 'BuildingsAndImprovementsGross', 'BusinessAcquisitionCostOfAcquiredEntityCashPaid', 'BusinessAcquisitionProFormaEarningsPerShareDiluted', 'BusinessAcquisitionsProFormaNetIncomeLoss', 'BusinessAcquisitionsProFormaRevenue', 'BusinessCombinationIntegrationRelatedCosts', 'BusinessCombinationRecognizedIdentifiableAssetsAcquiredAndLiabilitiesAssumedIntangibles', 'CapitalizedComputerSoftwareAmortization', 'CapitalizedComputerSoftwareAmortization1', 'CapitalLeasedAssetsGross', 'CapitalLeaseObligationsIncurred', 'CapitalLeasesFutureMinimumPaymentsDue', 'CapitalLeasesFutureMinimumPaymentsDueCurrent', 'CapitalLeasesFutureMinimumPaymentsDueInFiveYears', 'CapitalLeasesFutureMinimumPaymentsDueInFourYears', 'CapitalLeasesFutureMinimumPaymentsDueInThreeYears', 'CapitalLeasesFutureMinimumPaymentsDueInTwoYears', 'CapitalLeasesFutureMinimumPaymentsDueThereafter', 'CapitalLeasesFutureMinimumPaymentsInterestIncludedInPayments', 'CapitalLeasesFutureMinimumPaymentsRemainderOfFiscalYear', 'CapitalLeasesLesseeBalanceSheetAssetsByMajorClassAccumulatedDeprecation', 'CashAndCashEquivalentsAtCarryingValue', 'CashAndCashEquivalentsPeriodIncreaseDecrease', 'CashCashEquivalentsAndShortTermInvestments', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect', 'CommercialPaper', 'CommonStockDividendsPerShareDeclared', 'CommonStockIncludingAdditionalPaidInCapital', 'CommonStockSharesAuthorized', 'CommonStockSharesOutstanding', 'CommonStocksIncludingAdditionalPaidInCapital', 'ComprehensiveIncomeNetOfTax', 'ContractWithCustomerLiability', 'ContractWithCustomerLiabilityCurrent', 'ContractWithCustomerLiabilityNoncurrent', 'ContractWithCustomerLiabilityRevenueRecognized', 'ConvertibleDebtCurrent', 'CostMethodInvestments', 'CostOfGoodsAndServicesSold', 'CostOfGoodsSold', 'CostOfRevenue', 'CostsAndExpenses', 'CumulativeEffectOfInitialAdoptionOfFIN48', 'CumulativeEffectOfInitialAdoptionOfNewAccountingPrinciple', 'CurrentFederalTaxExpenseBenefit', 'CurrentForeignTaxExpenseBenefit', 'CurrentIncomeTaxExpenseBenefit', 'CurrentStateAndLocalTaxExpenseBenefit', 'DebtInstrumentCarryingAmount', 'DebtInstrumentFaceAmount', 'DebtInstrumentPrincipalOutstanding', 'DebtInstrumentUnamortizedDiscount', 'DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet', 'DebtLongtermAndShorttermCombinedAmount', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLonger', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12Months', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'DebtSecuritiesAvailableForSaleRealizedGain', 'DebtSecuritiesAvailableForSaleRealizedLoss', 'DebtSecuritiesAvailableForSaleUnrealizedLossPosition', 'DebtSecuritiesAvailableForSaleUnrealizedLossPositionAccumulatedLoss', 'DeferredFederalIncomeTaxExpenseBenefit', 'DeferredFederalStateAndLocalTaxExpenseBenefit', 'DeferredForeignIncomeTaxExpenseBenefit', 'DeferredIncomeTaxExpenseBenefit', 'DeferredIncomeTaxesAndTaxCredits', 'DeferredIncomeTaxLiabilities', 'DeferredIncomeTaxLiabilitiesNet', 'DeferredRevenue', 'DeferredRevenueAdditions', 'DeferredRevenueCurrent', 'DeferredRevenueNoncurrent', 'DeferredRevenueRevenueRecognized', 'DeferredRevenueRevenueRecognized1', 'DeferredStateAndLocalIncomeTaxExpenseBenefit', 'DeferredTaxAssetsCapitalLossCarryforwards', 'DeferredTaxAssetsDeferredIncome', 'DeferredTaxAssetsGross', 'DeferredTaxAssetsLiabilitiesNet', 'DeferredTaxAssetsLiabilitiesNetCurrent', 'DeferredTaxAssetsLiabilitiesNetNoncurrent', 'DeferredTaxAssetsNet', 'DeferredTaxAssetsNetCurrent', 'DeferredTaxAssetsNetNoncurrent', 'DeferredTaxAssetsOperatingLossCarryforwards', 'DeferredTaxAssetsOther', 'DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost', 'DeferredTaxAssetsTaxDeferredExpenseOther', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsImpairmentLosses', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsOther', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsRestructuringCharges', 'DeferredTaxAssetsValuationAllowance', 'DeferredTaxLiabilities', 'DeferredTaxLiabilitiesLeasingArrangements', 'DeferredTaxLiabilitiesNoncurrent', 'DeferredTaxLiabilitiesOther', 'DeferredTaxLiabilitiesOtherComprehensiveIncome', 'DeferredTaxLiabilitiesTaxDeferredIncome', 'DeferredTaxLiabilitiesUndistributedForeignEarnings', 'DeferredTaxLiabilityNotRecognizedAmountOfUnrecognizedDeferredTaxLiability', 'DeferredTaxLiabilityNotRecognizedAmountOfUnrecognizedDeferredTaxLiabilityUndistributedEarningsOfForeignSubsidiaries', 'DeferredTaxLiabilityNotRecognizedCumulativeAmountOfTemporaryDifference', 'DefinedContributionPlanCostRecognized', 'DefinedContributionPlanEmployerMatchingContributionPercentOfMatch', 'DefinedContributionPlanMaximumAnnualContributionPerEmployeePercent', 'DefinedContributionPlanMaximumAnnualContributionsPerEmployeePercent', 'DepositsReceivedForSecuritiesLoanedAtCarryingValue', 'Depreciation', 'DerivativeAssetDesignatedAsHedgingInstrumentFairValue', 'DerivativeAssetFairValueGrossAssetIncludingNotSubjectToMasterNettingArrangement', 'DerivativeAssetFairValueGrossLiability', 'DerivativeAssetNotDesignatedAsHedgingInstrumentFairValue', 'DerivativeAssets', 'DerivativeCollateralObligationToReturnCash', 'DerivativeCollateralRightToReclaimCash', 'DerivativeFairValueOfDerivativeAsset', 'DerivativeFairValueOfDerivativeLiability', 'DerivativeInstrumentsNotDesignatedAsHedgingInstrumentsGainLossNet', 'DerivativeLiabilities', 'DerivativeLiabilityFairValueGrossAsset', 'DerivativeLiabilityFairValueGrossLiabilityIncludingNotSubjectToMasterNettingArrangement', 'DerivativePriceRiskOptionStrikePrice', 'DividendsCommonStockCash', 'DividendsStock', 'EarningsPerShareBasic', 'EarningsPerShareDiluted', 'EffectiveIncomeTaxRateContinuingOperations', 'EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate', 'EffectiveIncomeTaxRateReconciliationDeductionsQualifiedProductionActivities', 'EffectiveIncomeTaxRateReconciliationForeignIncomeTaxRateDifferential', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpense', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost', 'EffectiveIncomeTaxRateReconciliationOtherAdjustments', 'EffectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes', 'EffectiveIncomeTaxRateReconciliationTaxCreditsResearch', 'EffectiveIncomeTaxRateReconciliationTaxSettlementsDomestic', 'EffectOfExchangeRateOnCashAndCashEquivalents', 'EmployeeRelatedLiabilitiesCurrent', 'EmployeeServiceShareBasedCompensationCashReceivedFromExerciseOfStockOptions', 'EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense', 'EmployeeServiceShareBasedCompensationTaxBenefitRealizedFromExerciseOfStockOptions', 'EntityWideDisclosureOnGeographicAreasLongLivedAssetsInEntitysCountryOfDomicile', 'EntityWideDisclosureOnGeographicAreasLongLivedAssetsInForeignCountries', 'EntityWideDisclosureOnGeographicAreasRevenueFromExternalCustomersAttributedToEntitysCountryOfDomicile', 'EntityWideDisclosureOnGeographicAreasRevenueFromExternalCustomersAttributedToForeignCountries', 'EquitySecuritiesFvNiRealizedGainLoss', 'EquitySecuritiesFvNiUnrealizedGainLoss', 'EquitySecuritiesWithoutReadilyDeterminableFairValueAmount', 'ExcessTaxBenefitFromShareBasedCompensationFinancingActivities', 'ExcessTaxBenefitFromShareBasedCompensationOperatingActivities', 'FairValueAssetsMeasuredOnRecurringBasisCashAndCashEquivalents', 'FairValueAssetsMeasuredOnRecurringBasisChangeInUnrealizedGainLossIncludedInOtherIncome', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInEarnings', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInEarnings1', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInOtherComprehensiveIncome', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInOtherComprehensiveIncomeLoss', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetPurchases', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetPurchasesSalesIssuancesSettlements', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetTransfersNet', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetTransfersOutOfLevel3', 'FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', 'FinanceLeaseInterestExpense', 'FinanceLeaseInterestPaymentOnLiability', 'FinanceLeaseLiability', 'FinanceLeaseLiabilityPaymentsDue', 'FinanceLeaseLiabilityPaymentsDueAfterYearFive', 'FinanceLeaseLiabilityPaymentsDueNextTwelveMonths', 'FinanceLeaseLiabilityPaymentsDueYearFive', 'FinanceLeaseLiabilityPaymentsDueYearFour', 'FinanceLeaseLiabilityPaymentsDueYearThree', 'FinanceLeaseLiabilityPaymentsDueYearTwo', 'FinanceLeaseLiabilityPaymentsRemainderOfFiscalYear', 'FinanceLeaseLiabilityUndiscountedExcessAmount', 'FinanceLeasePrincipalPayments', 'FinanceLeaseRightOfUseAsset', 'FinanceLeaseRightOfUseAssetAmortization', 'FinanceLeaseWeightedAverageDiscountRatePercent', 'FiniteLivedIntangibleAssetsAccumulatedAmortization', 'FiniteLivedIntangibleAssetsAmortizationExpense', 'FiniteLivedIntangibleAssetsAmortizationExpenseAfterYearFive', 'FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths', 'FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFive', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFour', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearThree', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo', 'FiniteLivedIntangibleAssetsGross', 'FiniteLivedIntangibleAssetsNet', 'FiniteLivedIntangibleAssetsUsefulLifeMaximum', 'FiniteLivedIntangibleAssetsUsefulLifeMinimum', 'FinitelivedIntangibleAssetsAcquired1', 'ForeignCurrencyCashFlowHedgeGainLossReclassifiedToEarningsNet', 'ForeignCurrencyCashFlowHedgeGainLossToBeReclassifiedDuringNext12Months', 'ForeignCurrencyTransactionGainLossBeforeTax', 'FurnitureAndFixturesGross', 'FutureAmortizationExpenseAfterYearFive', 'FutureAmortizationExpenseYearFive', 'FutureAmortizationExpenseYearFour', 'FutureAmortizationExpenseYearOne', 'FutureAmortizationExpenseYearThree', 'FutureAmortizationExpenseYearTwo', 'GainLossOnComponentsExcludedFromAssessmentOfForeignCurrencyCashFlowHedgeEffectiveness', 'GainLossOnDerivativeInstrumentsNetPretax', 'GainLossOnInvestments', 'GeneralAndAdministrativeExpense', 'Goodwill', 'GoodwillAcquiredDuringPeriod', 'GoodwillImpairedAccumulatedImpairmentLoss', 'GoodwillImpairmentLoss', 'GoodwillOtherChanges', 'GoodwillOtherIncreaseDecrease', 'GoodwillWrittenOffRelatedToSaleOfBusinessUnit', 'GrossProfit', 'HeldToMaturitySecurities', 'HeldToMaturitySecuritiesAccumulatedUnrecognizedHoldingGain', 'HeldToMaturitySecuritiesAccumulatedUnrecognizedHoldingLoss', 'HeldToMaturitySecuritiesAmortizedCostBeforeOtherThanTemporaryImpairment', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionLessThanTwelveMonthsFairValue', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionTwelveMonthsOrLongerFairValue', 'HeldToMaturitySecuritiesFairValue', 'ImpairmentEffectOnEarningsPerShareAfterTax', 'ImpairmentOfInvestments', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesDomestic', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments', 'IncomeTaxExpenseBenefit', 'IncomeTaxesPaidNet', 'IncreaseDecreaseInAccountsPayable', 'IncreaseDecreaseInAccountsReceivable', 'IncreaseDecreaseInAccruedIncomeTaxesPayable', 'IncreaseDecreaseInCashCollateralForLoanedSecurities', 'IncreaseDecreaseInCollateralHeldUnderSecuritiesLending', 'IncreaseDecreaseInContractWithCustomerLiability', 'IncreaseDecreaseInDeferredRevenue', 'IncreaseDecreaseInInventories', 'IncreaseDecreaseInOtherCurrentAssets', 'IncreaseDecreaseInOtherCurrentLiabilities', 'IncreaseDecreaseInOtherNoncurrentAssets', 'IncreaseDecreaseInOtherNoncurrentLiabilities', 'IncrementalCommonSharesAttributableToShareBasedPaymentArrangements', 'IntangibleAssetsNetExcludingGoodwill', 'InterestExpense', 'InterestPaid', 'InventoryAdjustments', 'InventoryFinishedGoods', 'InventoryFinishedGoodsNetOfReserves', 'InventoryNet', 'InventoryRawMaterials', 'InventoryRawMaterialsNetOfReserves', 'InventoryWorkInProcess', 'InventoryWorkInProcessNetOfReserves', 'InvestmentIncomeInterestAndDividend', 'InvestmentIncomeNet', 'Land', 'LeaseAndRentalExpense', 'LeaseholdImprovementsGross', 'LesseeOperatingLeaseLiabilityPaymentsDue', 'LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFour', 'LesseeOperatingLeaseLiabilityPaymentsDueYearThree', 'LesseeOperatingLeaseLiabilityPaymentsDueYearTwo', 'LesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear', 'LesseeOperatingLeaseLiabilityUndiscountedExcessAmount', 'Liabilities', 'LiabilitiesAndStockholdersEquity', 'LiabilitiesCurrent', 'LineOfCreditFacilityCurrentBorrowingCapacity', 'LineOfCreditFacilityMaximumBorrowingCapacity', 'LitigationReserveNoncurrent', 'LongTermDebt', 'LongTermDebtCurrent', 'LongTermDebtFairValue', 'LongTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo', 'LongTermDebtMaturitiesRepaymentsOfPrincipalRemainderOfFiscalYear', 'LongTermDebtNoncurrent', 'LongTermInvestments', 'LongTermNotesPayable', 'LossContingencyAccrualCarryingValueCurrent', 'LossContingencyRangeOfPossibleLossPortionNotAccrued', 'MarketableSecuritiesRealizedGainLossOtherThanTemporaryImpairmentsAmount', 'MinorityInterestOwnershipPercentageByParent', 'NetCashProvidedByUsedInFinancingActivities', 'NetCashProvidedByUsedInFinancingActivitiesContinuingOperations', 'NetCashProvidedByUsedInInvestingActivities', 'NetCashProvidedByUsedInInvestingActivitiesContinuingOperations', 'NetCashProvidedByUsedInOperatingActivities', 'NetCashProvidedByUsedInOperatingActivitiesContinuingOperations', 'NetIncomeLoss', 'NoncashOrPartNoncashAcquisitionFixedAssetsAcquired1', 'NoncurrentAssets', 'NonoperatingIncomeExpense', 'NumberOfBusinessesAcquired', 'NumberOfReportableSegments', 'OperatingExpenses', 'OperatingIncomeLoss', 'OperatingLeaseCost', 'OperatingLeaseImpairmentLoss', 'OperatingLeaseLiability', 'OperatingLeaseLiabilityNoncurrent', 'OperatingLeasePayments', 'OperatingLeaseRightOfUseAsset', 'OperatingLeaseWeightedAverageDiscountRatePercent', 'OperatingLossCarryforwards', 'OptionIndexedToIssuersEquityStrikePrice', 'OtherAccruedLiabilitiesNoncurrent', 'OtherAssets', 'OtherAssetsCurrent', 'OtherAssetsFairValueDisclosure', 'OtherAssetsNoncurrent', 'OtherComprehensiveIncomeAvailableForSaleSecuritiesAdjustmentNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeDerivativesQualifyingAsHedgesNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeForeignCurrencyTransactionAndTranslationAdjustmentNetOfTaxPeriodIncreaseDecrease', 'OtherComprehensiveIncomeForeignCurrencyTranslationAdjustmentTax', 'OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'OtherComprehensiveIncomeLossAvailableForSaleSecuritiesTax', 'OtherComprehensiveIncomeLossCashFlowHedgeGainLossAfterReclassificationAndTax', 'OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesNetOfTax', 'OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesTax', 'OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax', 'OtherComprehensiveIncomeLossForeignCurrency

In [ ]:
capex = data["facts"]["us-gaap"]["PaymentsToAcquirePropertyPlantAndEquipment"]["units"]["USD"]

capex_df = pd.DataFrame(capex)

capex_df.head()

,start,end,val,accn,fy,fp,form,filed,frame
0,2007-07-01,2008-06-30,3182000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008
1,2008-07-01,2008-09-30,778000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,CY2008Q3
2,2008-07-01,2008-12-31,1620000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,NaN
3,2008-10-01,2008-12-31,842000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,CY2008Q4
4,2008-07-01,2009-03-31,2252000000,0001193125-10-090116,2010.0,Q3,10-Q,2010-04-22,NaN

In [ ]:
capex_df["start"] = pd.to_datetime(capex_df["start"])
capex_df["end"] = pd.to_datetime(capex_df["end"])

In [ ]:
capex_df["duration"] = capex_df["end"] - capex_df["start"]

In [ ]:
annual_capex_df = capex_df[
    (capex_df["duration"] >= pd.Timedelta(days=350)) &
    (capex_df["duration"] <= pd.Timedelta(days=380)) &
    (capex_df["form"] == "10-K")
].copy()

In [ ]:
annual_capex_df

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2007-07-01,2008-06-30,3182000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008,365 days
6,2008-07-01,2009-06-30,3119000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN,364 days
7,2008-07-01,2009-06-30,3119000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2009,364 days
18,2009-07-01,2010-06-30,1977000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN,364 days
19,2009-07-01,2010-06-30,1977000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,NaN,364 days
20,2009-07-01,2010-06-30,1977000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2010,364 days
31,2010-07-01,2011-06-30,2355000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,NaN,364 days
32,2010-07-01,2011-06-30,2355000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,NaN,364 days
33,2010-07-01,2011-06-30,2355000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
45,2011-07-01,2012-06-30,2305000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,NaN,365 days
46,2011-07-01,2012-06-30,2305000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,365 days
48,2011-07-01,2012-06-30,2305000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2012,365 days
59,2012-07-01,2013-06-30,4257000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
61,2012-07-01,2013-06-30,4257000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,NaN,364 days
62,2012-07-01,2013-06-30,4257000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
74,2013-07-01,2014-06-30,5485000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,NaN,364 days
75,2013-07-01,2014-06-30,5485000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
77,2013-07-01,2014-06-30,5485000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,CY2014,364 days
88,2014-07-01,2015-06-30,5944000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
90,2014-07-01,2015-06-30,5944000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,NaN,364 days
91,2014-07-01,2015-06-30,5944000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2015,364 days
102,2015-07-01,2016-06-30,8343000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,NaN,365 days
103,2015-07-01,2016-06-30,8343000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,NaN,365 days
104,2015-07-01,2016-06-30,8343000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016,365 days
115,2016-07-01,2017-06-30,8129000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,NaN,364 days
116,2016-07-01,2017-06-30,8129000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,NaN,364 days
117,2016-07-01,2017-06-30,8129000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,CY2017,364 days
128,2017-07-01,2018-06-30,11632000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,NaN,364 days
129,2017-07-01,2018-06-30,11632000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,NaN,364 days
130,2017-07-01,2018-06-30,11632000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,CY2018,364 days
141,2018-07-01,2019-06-30,13925000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,NaN,364 days
142,2018-07-01,2019-06-30,13925000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,NaN,364 days
143,2018-07-01,2019-06-30,13925000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,CY2019,364 days
154,2019-07-01,2020-06-30,15441000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,NaN,365 days
155,2019-07-01,2020-06-30,15441000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,NaN,365 days
156,2019-07-01,2020-06-30,15441000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,CY2020,365 days
167,2020-07-01,2021-06-30,20622000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,NaN,364 days
168,2020-07-01,2021-06-30,20622000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,NaN,364 days
169,2020-07-01,2021-06-30,20622000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,CY2021,364 days
180,2021-07-01,2022-06-30,23886000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,NaN,364 days
181,2021-07-01,2022-06-30,23886000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,NaN,364 days
182,2021-07-01,2022-06-30,23886000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
194,2022-07-01,2023-06-30,28107000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,NaN,364 days
195,2022-07-01,2023-06-30,28107000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
197,2022-07-01,2023-06-30,28107000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,CY2023,364 days
208,2023-07-01,2024-06-30,44477000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,365 days
210,2023-07-01,2024-06-30,44477000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,NaN,365 days
211,2023-07-01,2024-06-30,44477000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2024,365 days
222,2024-07-01,2025-06-30,64551000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,NaN,364 days
223,2024-07-01,2025-06-30,64551000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
229,2025-07-01,2026-06-30,115948000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_capex_df = annual_capex_df.sort_values("filed")

In [ ]:
annual_capex_df = annual_capex_df.drop_duplicates(
    subset=["start", "end"],
    keep="last"
)

In [ ]:
annual_capex_df

,start,end,val,accn,fy,fp,form,filed,frame,duration
0,2007-07-01,2008-06-30,3182000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008,365 days
7,2008-07-01,2009-06-30,3119000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2009,364 days
20,2009-07-01,2010-06-30,1977000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2010,364 days
33,2010-07-01,2011-06-30,2355000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN,364 days
48,2011-07-01,2012-06-30,2305000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2012,365 days
62,2012-07-01,2013-06-30,4257000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN,364 days
77,2013-07-01,2014-06-30,5485000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,CY2014,364 days
91,2014-07-01,2015-06-30,5944000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,CY2015,364 days
104,2015-07-01,2016-06-30,8343000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016,365 days
117,2016-07-01,2017-06-30,8129000000,0001564590-19-027952,2019.0,FY,10-K,2019-08-01,CY2017,364 days
130,2017-07-01,2018-06-30,11632000000,0001564590-20-034944,2020.0,FY,10-K,2020-07-30,CY2018,364 days
143,2018-07-01,2019-06-30,13925000000,0001564590-21-039151,2021.0,FY,10-K,2021-07-29,CY2019,364 days
156,2019-07-01,2020-06-30,15441000000,0001564590-22-026876,2022.0,FY,10-K,2022-07-28,CY2020,365 days
169,2020-07-01,2021-06-30,20622000000,0000950170-23-035122,2023.0,FY,10-K,2023-07-27,CY2021,364 days
182,2021-07-01,2022-06-30,23886000000,0000950170-24-087843,2024.0,FY,10-K,2024-07-30,NaN,364 days
197,2022-07-01,2023-06-30,28107000000,0000950170-25-100235,2025.0,FY,10-K,2025-07-30,CY2023,364 days
223,2024-07-01,2025-06-30,64551000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2025,364 days
211,2023-07-01,2024-06-30,44477000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2024,365 days
229,2025-07-01,2026-06-30,115948000000,0001193125-26-323660,2026.0,FY,10-K,2026-07-29,CY2026,364 days

In [ ]:
annual_capex_df["fiscal_year"] = annual_capex_df["end"].dt.year

In [ ]:
capex_final = annual_capex_df[
    ["fiscal_year", "val"]
].copy()

capex_final = capex_final.rename(
    columns={"val": "capex"}
)

In [ ]:
capex_final = capex_final[
    (capex_final["fiscal_year"] >= 2016) &
    (capex_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
capex_final

    fiscal_year         capex
0          2016    8343000000
1          2017    8129000000
2          2018   11632000000
3          2019   13925000000
4          2020   15441000000
5          2021   20622000000
6          2022   23886000000
7          2023   28107000000
8          2024   44477000000
9          2025   64551000000
10         2026  115948000000

In [ ]:
financials_final = financials_final.merge(
    capex_final,
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_final["free_cash_flow"] = (
    financials_final["operating_cash_flow"]
    - financials_final["capex"]
)

In [ ]:
financials_final[["fiscal_year", "operating_cash_flow", "capex", "free_cash_flow"]]

    fiscal_year  operating_cash_flow         capex  free_cash_flow
0          2016          33325000000    8343000000     24982000000
1          2017          39507000000    8129000000     31378000000
2          2018          43884000000   11632000000     32252000000
3          2019          52185000000   13925000000     38260000000
4          2020          60675000000   15441000000     45234000000
5          2021          76740000000   20622000000     56118000000
6          2022          89035000000   23886000000     65149000000
7          2023          87582000000   28107000000     59475000000
8          2024         118548000000   44477000000     74071000000
9          2025         136162000000   64551000000     71611000000
10         2026         182935000000  115948000000     66987000000

In [ ]:
financials_final["free_cash_flow_margin"] = (
    financials_final["free_cash_flow"]
    / financials_final["revenue"]
    * 100
)

In [ ]:
financials_final[
    ["fiscal_year", "revenue", "free_cash_flow", "free_cash_flow_margin"]
]

    fiscal_year       revenue  free_cash_flow  free_cash_flow_margin
0          2016   91154000000     24982000000              27.406367
1          2017   96571000000     31378000000              32.492156
2          2018  110360000000     32252000000              29.224357
3          2019  125843000000     38260000000              30.402962
4          2020  143015000000     45234000000              31.628850
5          2021  168088000000     56118000000              33.386083
6          2022  198270000000     65149000000              32.858728
7          2023  211915000000     59475000000              28.065498
8          2024  245122000000     74071000000              30.218014
9          2025  281724000000     71611000000              25.418850
10         2026  331839000000     66987000000              20.186597

In [ ]:
"CashAndCashEquivalentsAtCarryingValue" in data["facts"]["us-gaap"]

True

In [ ]:
cash = data["facts"]["us-gaap"]["CashAndCashEquivalentsAtCarryingValue"]["units"]["USD"]

cash_df = pd.DataFrame(cash)

In [ ]:
cash_df.head()

,end,val,accn,fy,fp,form,filed,frame
0,2007-06-30,6111000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2007Q2I
1,2008-06-30,10339000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,NaN
2,2008-06-30,10339000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,NaN
3,2008-06-30,10339000000,0001193125-10-090116,2010.0,Q3,10-Q,2010-04-22,NaN
4,2008-06-30,10339000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN

In [ ]:
cash_df["end"] = pd.to_datetime(cash_df["end"])

In [ ]:
annual_cash = cash_df[
    (cash_df["form"] == "10-K")
].copy()

In [ ]:
annual_cash.head(20)

,end,val,accn,fy,fp,form,filed,frame
0,2007-06-30,6111000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2007Q2I
4,2008-06-30,10339000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN
5,2008-06-30,10339000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,CY2008Q2I
14,2009-06-30,6076000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN
18,2009-06-30,6076000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,NaN
19,2009-06-30,6076000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,CY2009Q2I
30,2010-06-30,5505000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,NaN
34,2010-06-30,5505000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,NaN
38,2010-06-30,5505000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,NaN
39,2010-06-30,5505000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN
51,2011-06-30,9610000000,0001193125-11-200680,2011.0,FY,10-K,2011-07-28,NaN
55,2011-06-30,9610000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,NaN
59,2011-06-30,9610000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN
61,2011-06-30,9610000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,CY2011Q2I
72,2012-06-30,6938000000,0001193125-12-316848,2012.0,FY,10-K,2012-07-26,NaN
76,2012-06-30,6938000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN
81,2012-06-30,6938000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,NaN
82,2012-06-30,6938000000,0001193125-15-272806,2015.0,FY,10-K,2015-07-31,NaN
94,2013-06-30,3804000000,0001193125-13-310206,2013.0,FY,10-K,2013-07-30,NaN
99,2013-06-30,3804000000,0001193125-14-289961,2014.0,FY,10-K,2014-07-31,NaN

In [ ]:
annual_cash = annual_cash.sort_values("filed")

In [ ]:
annual_cash = annual_cash.drop_duplicates(
    subset=["end"],
    keep="last"
)

In [ ]:
cash_final = annual_cash[
    ["end", "val"]
].copy()

cash_final["fiscal_year"] = cash_final["end"].dt.year

cash_final = cash_final.rename(
    columns={"val": "cash_and_equivalents"}
)

cash_final = cash_final[
    (cash_final["fiscal_year"] >= 2016) &
    (cash_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
cash_final

          end  cash_and_equivalents  fiscal_year
0  2016-06-30            6510000000         2016
1  2017-06-30            7663000000         2017
2  2018-06-30           11946000000         2018
3  2019-06-30           11356000000         2019
4  2020-06-30           13576000000         2020
5  2021-06-30           14224000000         2021
6  2022-06-30           13931000000         2022
7  2023-06-30           34704000000         2023
8  2024-06-30           18315000000         2024
9  2025-06-30           30242000000         2025
10 2026-06-30           20935000000         2026

In [ ]:
assets = data["facts"]["us-gaap"]["Assets"]["units"]["USD"]
assets_df = pd.DataFrame(assets)

In [ ]:
assets_df.head()

,end,val,accn,fy,fp,form,filed,frame
0,2009-06-30,77888000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,NaN
1,2009-06-30,77888000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,NaN
2,2009-06-30,77888000000,0001193125-10-090116,2010.0,Q3,10-Q,2010-04-22,NaN
3,2009-06-30,77888000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2009Q2I
4,2009-09-30,81612000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,CY2009Q3I

In [ ]:
assets_df["end"] = pd.to_datetime(assets_df["end"])

annual_assets = assets_df[
    assets_df["form"] == "10-K"
].copy()

annual_assets = annual_assets.sort_values("filed")

annual_assets = annual_assets.drop_duplicates(
    subset=["end"],
    keep="last"
)

In [ ]:
assets_final = annual_assets[
    ["end", "val"]
].copy()

assets_final["fiscal_year"] = assets_final["end"].dt.year

assets_final = assets_final.rename(
    columns={"val": "assets"}
)

assets_final = assets_final[
    (assets_final["fiscal_year"] >= 2016) &
    (assets_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
assets_final

          end        assets  fiscal_year
0  2016-06-30  193468000000         2016
1  2017-06-30  250312000000         2017
2  2018-06-30  258848000000         2018
3  2019-06-30  286556000000         2019
4  2020-06-30  301311000000         2020
5  2021-06-30  333779000000         2021
6  2022-06-30  364840000000         2022
7  2023-06-30  411976000000         2023
8  2024-06-30  512163000000         2024
9  2025-06-30  619003000000         2025
10 2026-06-30  758376000000         2026

In [ ]:
liabilities = data["facts"]["us-gaap"]["Liabilities"]["units"]["USD"]
liabilities_df = pd.DataFrame(liabilities)

In [ ]:
liabilities_df["end"] = pd.to_datetime(liabilities_df["end"])

annual_liabilities = liabilities_df[
    liabilities_df["form"] == "10-K"
].copy()

annual_liabilities = annual_liabilities.sort_values("filed")

annual_liabilities = annual_liabilities.drop_duplicates(
    subset=["end"],
    keep="last"
)

In [ ]:
liabilities_final = annual_liabilities[
    ["end", "val"]
].copy()

liabilities_final["fiscal_year"] = liabilities_final["end"].dt.year

liabilities_final = liabilities_final.rename(
    columns={"val": "liabilities"}
)

liabilities_final = liabilities_final[
    (liabilities_final["fiscal_year"] >= 2016) &
    (liabilities_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
liabilities_final

          end   liabilities  fiscal_year
0  2016-06-30  121471000000         2016
1  2017-06-30  162601000000         2017
2  2018-06-30  176130000000         2018
3  2019-06-30  184226000000         2019
4  2020-06-30  183007000000         2020
5  2021-06-30  191791000000         2021
6  2022-06-30  198298000000         2022
7  2023-06-30  205753000000         2023
8  2024-06-30  243686000000         2024
9  2025-06-30  275524000000         2025
10 2026-06-30  315989000000         2026

In [ ]:
equity = data["facts"]["us-gaap"]["StockholdersEquity"]["units"]["USD"]
equity_df = pd.DataFrame(equity)

equity_df.head()

,end,val,accn,fy,fp,form,filed,frame
0,2008-06-30,36286000000,0001193125-10-171791,2010.0,FY,10-K,2010-07-30,CY2008Q2I
1,2008-09-30,33594000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,CY2008Q3I
2,2008-12-31,34478000000,0001193125-10-015598,2010.0,Q2,10-Q,2010-01-28,CY2008Q4I
3,2009-03-31,36943000000,0001193125-10-090116,2010.0,Q3,10-Q,2010-04-22,CY2009Q1I
4,2009-06-30,39558000000,0001193125-09-212454,2010.0,Q1,10-Q,2009-10-23,NaN

In [ ]:
equity_df["end"] = pd.to_datetime(equity_df["end"])

annual_equity = equity_df[
    equity_df["form"] == "10-K"
].copy()

annual_equity = annual_equity.sort_values("filed")

annual_equity = annual_equity.drop_duplicates(
    subset=["end"],
    keep="last"
)

In [ ]:
equity_final = annual_equity[
    ["end", "val"]
].copy()

equity_final["fiscal_year"] = equity_final["end"].dt.year

equity_final = equity_final.rename(
    columns={"val": "equity"}
)

equity_final = equity_final[
    (equity_final["fiscal_year"] >= 2016) &
    (equity_final["fiscal_year"] <= 2026)
].sort_values("fiscal_year").reset_index(drop=True)

In [ ]:
equity_final

          end        equity  fiscal_year
0  2016-06-30   83090000000         2016
1  2017-06-30   87711000000         2017
2  2018-06-30   82718000000         2018
3  2019-06-30  102330000000         2019
4  2020-06-30  118304000000         2020
5  2021-06-30  141988000000         2021
6  2022-06-30  166542000000         2022
7  2023-06-30  206223000000         2023
8  2024-06-30  268477000000         2024
9  2025-06-30  343479000000         2025
10 2026-06-30  442387000000         2026

In [ ]:
financials_final = financials_final.merge(
    cash_final[["fiscal_year", "cash_and_equivalents"]],
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_final = financials_final.merge(
    assets_final[["fiscal_year", "assets"]],
    on="fiscal_year",
    how="left"
)

financials_final = financials_final.merge(
    liabilities_final[["fiscal_year", "liabilities"]],
    on="fiscal_year",
    how="left"
)

financials_final = financials_final.merge(
    equity_final[["fiscal_year", "equity"]],
    on="fiscal_year",
    how="left"
)

In [ ]:
financials_final.shape

(11, 22)

In [ ]:
financials_final.isnull().sum()

fiscal_year              0
revenue                  0
revenue_growth           1
cost_of_revenue          0
gross_profit             0
gross_margin             0
rd_expense               0
sm_expense               0
ga_expense               0
reconstructed_opex       0
operating_income         0
operating_margin         0
net_income               0
net_profit_margin        0
operating_cash_flow      0
capex                    0
free_cash_flow           0
free_cash_flow_margin    0
cash_and_equivalents     0
assets                   0
liabilities              0
equity                   0
dtype: int64

In [ ]:
financials_final["balance_check"] = (
    financials_final["assets"]
    - financials_final["liabilities"]
    - financials_final["equity"]
)

In [ ]:
financials_final[
    ["fiscal_year", "assets", "liabilities", "equity", "balance_check"]
]

    fiscal_year        assets   liabilities        equity  balance_check
0          2016  193468000000  121471000000   83090000000   -11093000000
1          2017  250312000000  162601000000   87711000000              0
2          2018  258848000000  176130000000   82718000000              0
3          2019  286556000000  184226000000  102330000000              0
4          2020  301311000000  183007000000  118304000000              0
5          2021  333779000000  191791000000  141988000000              0
6          2022  364840000000  198298000000  166542000000              0
7          2023  411976000000  205753000000  206223000000              0
8          2024  512163000000  243686000000  268477000000              0
9          2025  619003000000  275524000000  343479000000              0
10         2026  758376000000  315989000000  442387000000              0

In [ ]:
equity_df[
    equity_df["end"] == pd.Timestamp("2016-06-30")
]

,end,val,accn,fy,fp,form,filed,frame
93,2016-06-30,71997000000,0001193125-16-662209,2016.0,FY,10-K,2016-07-28,NaN
94,2016-06-30,71997000000,0001193125-16-742796,2017.0,Q1,10-Q,2016-10-20,NaN
95,2016-06-30,71997000000,0001564590-17-000654,2017.0,Q2,10-Q,2017-01-26,NaN
96,2016-06-30,71997000000,0001564590-17-007547,2017.0,Q3,10-Q,2017-04-27,NaN
97,2016-06-30,71997000000,0001564590-17-014900,2017.0,FY,10-K,2017-08-02,NaN
98,2016-06-30,83090000000,0001564590-18-019062,2018.0,FY,10-K,2018-08-03,CY2016Q2I

In [ ]:
equity_final.loc[
    equity_final["fiscal_year"] == 2016,
    "equity"
] = 71997000000

In [ ]:
financials_final["balance_check"] = (
    financials_final["assets"]
    - financials_final["liabilities"]
    - financials_final["equity"]
)

financials_final[
    ["fiscal_year", "assets", "liabilities", "equity", "balance_check"]
]

    fiscal_year        assets   liabilities        equity  balance_check
0          2016  193468000000  121471000000   83090000000   -11093000000
1          2017  250312000000  162601000000   87711000000              0
2          2018  258848000000  176130000000   82718000000              0
3          2019  286556000000  184226000000  102330000000              0
4          2020  301311000000  183007000000  118304000000              0
5          2021  333779000000  191791000000  141988000000              0
6          2022  364840000000  198298000000  166542000000              0
7          2023  411976000000  205753000000  206223000000              0
8          2024  512163000000  243686000000  268477000000              0
9          2025  619003000000  275524000000  343479000000              0
10         2026  758376000000  315989000000  442387000000              0

In [ ]:
equity_final[
    equity_final["fiscal_year"] == 2016
]

         end       equity  fiscal_year
0 2016-06-30  71997000000         2016

In [ ]:
financials_final.loc[
    financials_final["fiscal_year"] == 2016,
    "equity"
] = 71997000000

In [ ]:
financials_final["balance_check"] = (
    financials_final["assets"]
    - financials_final["liabilities"]
    - financials_final["equity"]
)

financials_final[
    ["fiscal_year", "assets", "liabilities", "equity", "balance_check"]
]

    fiscal_year        assets   liabilities        equity  balance_check
0          2016  193468000000  121471000000   71997000000              0
1          2017  250312000000  162601000000   87711000000              0
2          2018  258848000000  176130000000   82718000000              0
3          2019  286556000000  184226000000  102330000000              0
4          2020  301311000000  183007000000  118304000000              0
5          2021  333779000000  191791000000  141988000000              0
6          2022  364840000000  198298000000  166542000000              0
7          2023  411976000000  205753000000  206223000000              0
8          2024  512163000000  243686000000  268477000000              0
9          2025  619003000000  275524000000  343479000000              0
10         2026  758376000000  315989000000  442387000000              0

In [ ]:
financials_final = financials_final.drop(
    columns=["balance_check"]
)

In [ ]:
financials_final.shape

(11, 22)

In [ ]:
financials_final.columns

Index(['fiscal_year', 'revenue', 'revenue_growth', 'cost_of_revenue',
       'gross_profit', 'gross_margin', 'rd_expense', 'sm_expense',
       'ga_expense', 'reconstructed_opex', 'operating_income',
       'operating_margin', 'net_income', 'net_profit_margin',
       'operating_cash_flow', 'capex', 'free_cash_flow',
       'free_cash_flow_margin', 'cash_and_equivalents', 'assets',
       'liabilities', 'equity'],
      dtype='object')

In [ ]:
financials_final.shape

(11, 22)

In [221]:
financials_final.to_csv(
    "microsoft_financials.csv",
    index=False
)